### ISSUE TITLE
element.setAttribute("__proto__", …) throws TypeError.

### ISSUE THREAD

**Issue by mbostock** [tmpvar/jsdom#1034]
The following code:

```
var document = require("jsdom").jsdom();
var span = document.createElement("SPAN");
span.setAttribute("__proto__", "Hello");
```

Throws this TypeError:

```
TypeError: Object [ undefined ] has no method '$getNode'
    at Attr.<anonymous> (./node_modules/jsdom/lib/jsdom/level2/events.js:415:26)
    at AttributeList.$setNoNS (./node_modules/jsdom/lib/jsdom/level1/core.js:1085:12)
    at Attr.<anonymous> (./node_modules/jsdom/lib/jsdom/level2/events.js:413:12)
    at core.Element.setAttribute (./node_modules/jsdom/lib/jsdom/level2/core.js:124:20)
    at repl:1:7
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
```

**Comment by domenic** [comment]
Hah, good catch. Presumably just some use of `{}` that needs to get swapped out with `Object.create(null)` somewhere.

**Comment by Sebmaster** [comment]
Just checked with jsdom@3.1.1 and node@0.12.0, but can't reproduce.
@domenic can you?

Are you on iojs already or an old version of jsdom maybe?

**Comment by mbostock** [comment]
Yes, I was running an old version of Node (v0.10.35), though the latest JSDOM. The problem goes away after upgrading to Node 0.12 (though, I have to re-install JSDOM after upgrading).

**Comment by domenic** [comment]
Yeah, old V8 versions have a broken `Object.create(null)`.
