### ISSUE TITLE
TypeError: needs a 'context' argument.

### ISSUE THREAD

**Issue by blganesh101** [tmpvar/jsdom#1050]
I'm using mac and jsdom version 4.0.1
and following is my code 

       jsdom.env({
                        html: body,
                        scripts: ['http://code.jquery.com/jquery-1.6.min.js']
                , done: function(err, window){
                        var $ = window.jQuery;
                         
                        console.log($('title').text());
                        res.end($('title').text());
                      }
                });
        });

I get the following error

TypeError: needs a 'context' argument.
    at new Window (/Users/lgmagic/Techwalk/nettuts/nodetube/node_modules/jsdom/lib/jsdom/browser/Window.js:32:26)
    at Object.exports.jsdom (/Users/lgmagic/Techwalk/nettuts/nodetube/node_modules/jsdom/lib/jsdom.js:46:16)
    at processHTML (/Users/lgmagic/Techwalk/nettuts/nodetube/node_modules/jsdom/lib/jsdom.js:220:24)
    at Object.exports.env.exports.jsdom.env (/Users/lgmagic/Techwalk/nettuts/nodetube/node_modules/jsdom/lib/jsdom.js:122:5)
    at Request._callback (/Users/lgmagic/Techwalk/nettuts/nodetube/app.js:31:15)
    at Request.self.callback (/Users/lgmagic/Techwalk/nettuts/nodetube/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/lgmagic/Techwalk/nettuts/nodetube/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/lgmagic/Techwalk/nettuts/nodetube/node_modules/request/request.js:1187:12)

**Comment by domenic** [comment]
What version of io.js are you using?

**Comment by blganesh101** [comment]
version 0.1.6

**Comment by domenic** [comment]
Hmm, there is no 0.1.6 version of io.js, so I am not sure what you are saying.

**Comment by blganesh101** [comment]
I guess i skipped a few things here.. Im new to Node and IO. I thought you were referring to io module of Node.js
i was trying to build with Node.js and 
just read the documentation that it is no longer supported with Node.js and works only with io.js. 

My bad. i think you should mark this issue invalid.
