### ISSUE TITLE
memory leaks on large URLs

### ISSUE THREAD

**Issue by rickdog** [tmpvar/jsdom#1089]
jsdom.env({
  url: "http://www.nytimes.com/2015/04/19/business/energy-environment/solar-power-battle-puts-hawaii-at-forefront-of-worldwide-changes.html",

C:\Users\rickdog>npm -v jsdom
2.1.18

please advise

```
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:161:15)
    at Request.init (C:\Users\rickdog\node_modules\jsdom\node_modules\request\request.js:667:8)
    at Redirect.onResponse (C:\Users\rickdog\node_modules\jsdom\node_modules\request\lib\redirect.js:149:11)
    at Request.onRequestResponse (C:\Users\rickdog\node_modules\jsdom\node_modules\request\request.js:1108:22)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:399:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:89:23)
    at Socket.socketOnData (_http_client.js:290:20)
    at Socket.emit (events.js:95:17)
    at readableAddChunk (_stream_readable.js:143:16)
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:161:15)
    at Request.start (C:\Users\rickdog\node_modules\jsdom\node_modules\request\request.js:1001:8)
    at Request.end (C:\Users\rickdog\node_modules\jsdom\node_modules\request\request.js:1531:10)
    at end (C:\Users\rickdog\node_modules\jsdom\node_modules\request\request.js:734:14)
    at Immediate._onImmediate (C:\Users\rickdog\node_modules\jsdom\node_modules\request\request.js:748:7)
    at processImmediate [as _immediateCallback] (timers.js:321:17)
```

**Comment by inikulin** [comment]
Seems like it's not caused by the URL length, but by the multiple nested redirects. According to the fact that we have more than 11 redirects, seems like that page or some resource goes into infinite redirect loop. 
@rickdog Do you have [loading of the external resources](https://github.com/tmpvar/jsdom#external-resources) enabled?

**Comment by rickdog** [comment]
should I enable or disable external resources, and if to enable, which resources?
The following produces the same errors:

var jsdom = require("jsdom");

jsdom.defaultDocumentFeatures = {
    FetchExternalResources: false,
    ProcessExternalResources: false
};

jsdom.env({
  url: "http://www.nytimes.com/2015/04/19/business/energy-environment/solar-power-battle-puts-hawaii-at-forefront-of-worldwide-changes.html",
  done: function (errors, window) {
    console.log(window);
  }
});

**Comment by inikulin** [comment]
I assume that you are using latest jsdom.
Because
> C:\Users\rickdog>npm -v jsdom
2.1.18

actually prints npm version, not jsdom's.

**Comment by inikulin** [comment]
The bug is caused by the fact that we are not sharing our cookie jar with the request on the redirects. I will try to rollout a fix within a couple of days.
