### ISSUE TITLE
<select>.outerHTML breaks

### ISSUE THREAD

**Issue by Munter** [tmpvar/jsdom#1107]
```
require('jsdom').jsdom('<select><option value="foo"></option></select>').body.firstChild.outerHTML

TypeError: Cannot read property 'nodeType' of undefined
    at exports.domToHtml (/Users/munter/src/frontend-rails/node_modules/jsdom/lib/jsdom/browser/domtohtml.js:14:20)
    at outerHTML (/Users/munter/src/frontend-rails/node_modules/jsdom/lib/jsdom/level1/core.js:1390:12)
    at repl:1:90
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
```

**Comment by domenic** [comment]
Haha man I am literally writing the changelog for this now... fixed in master, release going out in like 5 minutes. https://github.com/tmpvar/jsdom/commit/a702d102984560ed379e365747bf7b668464ac71

**Comment by Munter** [comment]
Awesome :dancer: 

Will this be in the 3.x branch as well?

**Comment by domenic** [comment]
Nope, 3.x does not receive fixes.

**Comment by Munter** [comment]
Well, I need this and can't  do the switch. I guess you're loosing my further input then. Forking for now and evaluating alternatives then

**Comment by domenic** [comment]
Sounds good, that was always the intent of the io.js requirement.

**Comment by Joris-van-der-Wel** [comment]
Here's the specific patch you will need to fix it: https://github.com/tmpvar/jsdom/commit/a702d102984560ed379e365747bf7b668464ac71

Basically the issue was that <select> has a length property, which causes domToHtml to assume it is a list instead of a node

**Comment by Munter** [comment]
I gave up on the idea of running a fork of jsdom. I have other projects that I want to move on without having the overhead of maintaining legacy projects. I figured out a way to work with old jsdom versions in the assertion library where it failed for me.
