### ISSUE TITLE
Exception while trying to load html

### ISSUE THREAD

**Issue by jwarkentin** [tmpvar/jsdom#1133]
I'm getting the following stack trace whenever I try to load the html from http://www.ivpressonline.com/life/foolproof-signs-that-she-s-into-you/article_bcf80030-72c0-5ca9-887d-c755939e16e0.html

Since I need access to the raw text, I fetch it first then pass it in to `jsdom.env()`. This has worked fine for everything up to this point, but for some reason whenever I try to load that particular site's HTML it throws this error. It doesn't pass it through to the `errors` argument in the callback. As far as I can tell it's completely internal to jsdom and there's nothing I can do to resolve it. It's consistently reproducible though.

I should also add that the error is not thrown when loading by passing the url directly to `jsdom.env()`; however, as I mentioned that's not a possibility since I need access to the raw source. Regardless, it shouldn't be throwing an error instead of passing it through to the callback.

```
TypeError: Cannot read property 'style' of undefined
    at CSSStyleDeclaration.Object.defineProperties.cssText.set [as cssText] (/mnt/source/insight/node_modules/jsdom/node_modules/cssstyle/lib/CSSStyleDeclaration.js:180:77)
    at define.proto._attrModified (/mnt/source/insight/node_modules/jsdom/lib/jsdom/level2/html.js:429:29)
    at Object.exports.appendAttribute (/mnt/source/insight/node_modules/jsdom/lib/jsdom/living/attributes.js:202:11)
    at Object.exports.setAttributeValue (/mnt/source/insight/node_modules/jsdom/lib/jsdom/living/attributes.js:331:13)
    at setChild (/mnt/source/insight/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:190:18)
    at setChild (/mnt/source/insight/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:196:7)
    at setChild (/mnt/source/insight/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:196:7)
    at setChild (/mnt/source/insight/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:196:7)
    at setChild (/mnt/source/insight/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:196:7)
    at setChild (/mnt/source/insight/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:196:7)
    at setChild (/mnt/source/insight/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:196:7)
    at setChild (/mnt/source/insight/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:196:7)
    at setChild (/mnt/source/insight/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:196:7)
    at setChild (/mnt/source/insight/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:196:7)
    at setChild (/mnt/source/insight/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:196:7)
    at HtmlToDom.appendHtmlToElement [as appendHtmlToDocument] (/mnt/source/insight/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:56:9)
    at setInnerHTML (/mnt/source/insight/node_modules/jsdom/lib/jsdom/level1/core.js:55:27)
    at HTMLDocument.inheritFrom.write (/mnt/source/insight/node_modules/jsdom/lib/jsdom/level1/core.js:1205:7)
    at Object.exports.jsdom (/mnt/source/insight/node_modules/jsdom/lib/jsdom.js:89:21)
    at processHTML (/mnt/source/insight/node_modules/jsdom/lib/jsdom.js:231:24)
    at /mnt/source/insight/node_modules/jsdom/lib/jsdom.js:157:13
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:305:5)
```

**Comment by domenic** [comment]
Hmm, we recently changed related code in 5.4.0. Can you try with 5.3.0 and tell me if the error is still present? That would confirm I messed up with the 5.4.0 changes.

**Comment by jwarkentin** [comment]
Ah, 5.3 does the trick! That must be it.

**Comment by domenic** [comment]
Great, will try to get this fixed; thanks for discovering it!!

**Comment by domenic** [comment]
@jwarkentin can you try the new 5.4.3 release?

**Comment by jwarkentin** [comment]
The update fixed the problem! Thanks a ton!

**Comment by domenic** [comment]
Yay!
