### ISSUE TITLE
Can't bootstrap angular

### ISSUE THREAD

**Issue by justinmchase** [tmpvar/jsdom#1177]
I'm having trouble trying to get angular to work with jsdom. Is there a known reason why this wouldn't work?

I'm basically doing this:

```
jsdom.env(
	'<div></div>',
	[ path.resolve(__dirname, '..', '..', 'node_modules/angular/angular.js') ],
	function (err, window) {
		if(err) return console.log(err);
		window
			.angular
			.module('test-module', [])
			.run(callback);
		window
		 	.angular
		 	.bootstrap(window.document, ['test-module']);
	}
);
```

And it is giving me this error:
```
Error: [$injector:unpr] Unknown provider: errorProvider <- error
      http://errors.angularjs.org/1.4.3/$injector/unpr?p0=errorProvider%20%3C-%20error
          at e:/code/evolve/evolve-client-core/node_modules/angular/angular.js:68:12
          at e:/code/evolve/evolve-client-core/node_modules/angular/angular.js:4262:19
          at Object.getService [as get] (e:/code/evolve/evolve-client-core/node_modules/angular/angular.js:4409:39)
          at e:/code/evolve/evolve-client-core/node_modules/angular/angular.js:4267:45
          at getService (e:/code/evolve/evolve-client-core/node_modules/angular/angular.js:4409:39)
          at Object.invoke (e:/code/evolve/evolve-client-core/node_modules/angular/angular.js:4441:13)
          at e:/code/evolve/evolve-client-core/node_modules/angular/angular.js:4272:79
          at forEach (e:/code/evolve/evolve-client-core/node_modules/angular/angular.js:336:20)
          at createInjector (e:/code/evolve/evolve-client-core/node_modules/angular/angular.js:4272:3)
          at doBootstrap (e:/code/evolve/evolve-client-core/node_modules/angular/angular.js:1630:20)
```

Has anyone tried to bootstrap angular with jsdom? Am I doing something wrong?

**Comment by Joris-van-der-Wel** [comment]
I just tried this in jsdom master and also 5.6.1. I see no error

```javascript
'use strict';
const jsdom = require('../jsdom');

jsdom.env(
    '<div></div>',
    [ require.resolve('angular/angular') ],
    function (err, window) {
        if (err) { return console.error(err, err.stack); }

        window
            .angular
            .module('test-module', [])
            .run(function() {
                console.log('My Angular test module callback');
            });

        window
            .angular
            .bootstrap(window.document, ['test-module']);
    }
);
```

**Comment by justinmchase** [comment]
ah ha!

Simple but dumb mistake on my part. I was passing in `callback` into the run function, which it was looking at the arguments on the callback function (e.g. `error`) and attempting to resovle an errorProvider to call the function. Thank you so much!
