### ISSUE TITLE
Crash on HTMLs which contain "<!DOCTYPE>" 

### ISSUE THREAD

**Issue by sqd** [tmpvar/jsdom#1204]
A minimal HTML that would cause a crash
```html
<!DOCTYPE>
```
Stack trace:
```
    throw new DOMException(DOMException.INVALID_CHARACTER_ERR,
    ^
InvalidCharacterError
    at Object.exports.name (H:\wspider\node_modules\jsdom\lib\jsdom\living\helpers\validate-names.js:10:11)
    at Object.exports.qname (H:\wspider\node_modules\jsdom\lib\jsdom\living\helpers\validate-names.js:16:11)
    at Object.core.DOMImplementation.createDocumentType (H:\wspider\node_modules\jsdom\lib\jsdom\living\dom-implementation.js:14:19)
    at setChild (H:\wspider\node_modules\jsdom\lib\jsdom\browser\htmltodom.js:150:52)
    at HtmlToDom.appendHtmlToElement [as appendHtmlToDocument] (H:\wspider\node_modules\jsdom\lib\jsdom\browser\htmltodom.js:56:9)
    at setInnerHTML (H:\wspider\node_modules\jsdom\lib\jsdom\level1\core.js:59:27)
    at HTMLDocument.inheritFrom.write (H:\wspider\node_modules\jsdom\lib\jsdom\level1\core.js:1074:7)
    at Object.exports.jsdom (H:\wspider\node_modules\jsdom\lib\jsdom.js:90:21)
    at processHTML (H:\wspider\node_modules\jsdom\lib\jsdom.js:232:24)
    at H:\wspider\node_modules\jsdom\lib\jsdom.js:205:7
```
Test code:
```javascript
var jsdom = require("jsdom");
jsdom.env("http://testhost/test_page.html", [], function(err, window){});
```

**Comment by sqd** [comment]
jsdom@6.1.0
iojs v3.3.3

**Comment by Sebmaster** [comment]
Seems like we shouldn't call verify at all in this case. Everything the parser says we'll basically have to take for granted. Might need a noVerify helper method here I think?

**Comment by domenic** [comment]
Great find, sorry about this.

What do browsers do? Do they create a doctype with weird info in it, or do they treat it as a bogus comment, or what?

**Comment by Sebmaster** [comment]
They just create a doctype with an empty name property.

**Comment by domenic** [comment]
Yeah then we definitely need a no-verify version of doctype creation. Will fix.
