### ISSUE TITLE
Tests relying on external resource are failing (resource was removed)

### ISSUE THREAD

**Issue by jeffcarp** [tmpvar/jsdom#1210]
[A test](https://github.com/tmpvar/jsdom/blob/master/test/jsdom/index.js#L195) in `test/jsdom/index.js` relies on fetching this external file:
`http://documentcloud.github.com/backbone/examples/todos/index.html`

However, that resource no longer exists. It's 404ing, which is breaking the two related assertions.

```
jsdom/index.js: ..........F..........................................................................
AssertionError: 'undefined' == 'function'
    at Object.equal (/home/vagrant/gh/jeffcarp/jsdom/node_modules/nodeunit/lib/types.js:83:39)
    at Object.done (/home/vagrant/gh/jeffcarp/jsdom/test/jsdom/index.js:206:14)
    at /home/vagrant/gh/jeffcarp/jsdom/lib/jsdom.js:254:18
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)

AssertionError: 'undefined' == 'function'
    at Object.equal (/home/vagrant/gh/jeffcarp/jsdom/node_modules/nodeunit/lib/types.js:83:39)
    at Object.done (/home/vagrant/gh/jeffcarp/jsdom/test/jsdom/index.js:207:14)
    at /home/vagrant/gh/jeffcarp/jsdom/lib/jsdom.js:254:18
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

**Comment by jeffcarp** [comment]
A suitable replacement URL could be: http://backbonejs.org/examples/todos/index.html

I ran the tests against that and they pass.

**Comment by domenic** [comment]
I knew that test was going to get us one day. Ideally we should set up a local server that serves a similarly-complicated package. But yeah, in the meantime happy to just substitute the URL.
