### ISSUE TITLE
TypeError: Invalid URL when supplying a HTML fragment

### ISSUE THREAD

**Issue by rkubik** [tmpvar/jsdom#1277]
Hi,

I am using node's builtin http module to fetch HTML from a URL (I understand jsdom allows you to do this but I need finer control over the request), the resulting HTML string is then fed into jsdom which throws a `TypeError: Invalid URL` Error. Not sure why the HTML is being detected and validated as a URL. The HTML looks fine, I've printed it out to screen before the jsdom request to make sure.

HTML:

    <html>
    <head>
    <title>
    ...
    </body>
    </html>

My code:

    var html = result from http.request(...)

    console.log(html);

    jsdom.env({
        html,
        src: [jquery],
        done: function (err, window) {
            if (err) {
                return callback(new Error('jsdom error: ' + err.message));
            }
            window.close();
            callback();
        }
    });

Stacktrace:

    TypeError: Invalid URL
        at URLStateMachine.parseNoScheme [as parse3] (/home/user/projects/git/apper/api/node_modules/jsdom/node_modules/whatwg-url-compat/lib/url.js:564:11)
        at new URLStateMachine (/home/user/projects/git/apper/api/node_modules/jsdom/node_modules/whatwg-url-compat/lib/url.js:497:35)
        at URL.init (/home/user/projects/git/apper/api/node_modules/jsdom/node_modules/whatwg-url-compat/lib/url.js:1328:21)
        at new URL (/home/user/projects/git/apper/api/node_modules/jsdom/node_modules/whatwg-url-compat/lib/url.js:1344:10)
        at loadFrame (/home/user/projects/git/apper/api/node_modules/jsdom/lib/jsdom/level2/html.js:1938:16)
        at define.proto._attach (/home/user/projects/git/apper/api/node_modules/jsdom/lib/jsdom/level2/html.js:2021:9)
        at core.Node._attach (/home/user/projects/git/apper/api/node_modules/jsdom/lib/jsdom/level1/core.js:491:15)
        at core.Node._attach (/home/user/projects/git/apper/api/node_modules/jsdom/lib/jsdom/level1/core.js:491:15)
        at core.Node._attach (/home/user/projects/git/apper/api/node_modules/jsdom/lib/jsdom/level1/core.js:491:15)
        at core.Node._attach (/home/user/projects/git/apper/api/node_modules/jsdom/lib/jsdom/level1/core.js:491:15)

Versions:

    jsdom@7.0.2
    node@v4.2.1

**Comment by Sebmaster** [comment]
The html apparently contains a frame which specifies an unresolveable URL.

It shouldn't throw a crashing stacktrace though and just provide it in the callback or in `window.onerror`, so that's a bug.

**Comment by rkubik** [comment]
The iframe's (there are four of them) use relative `src` attributes:

    <iframe src="/ads/728x90.html"

Based on `https://html.spec.whatwg.org` an iframe's src can be relative or absolute. I'm not understanding why the relative url `/ads/728x90.html` does not get resolved?

**Comment by Sebmaster** [comment]
Oh wow, I know. You don't set the url option, which causes it to default to about:blank. And you can't resolve anything from `about:blank` (except anchors) which causes it to fail.

**Comment by rkubik** [comment]
Ah, makes sense. Thanks.

**Comment by webjay** [comment]
I'm using `7.1.0` and it crashes when I give it the source of this page:
https://x.ai/live-ai-assistant-demo-ny-enterprise-technology-meetup/

It might be caused by: `<iframe src="//www.youtube.com/embed/iTvDKalbkqU" width="640" height="360" frameborder="0" allowfullscreen="allowfullscreen"></iframe>`

**Comment by domenic** [comment]
Did you set the `url` option to `"https://x.ai/live-ai-assistant-demo-ny-enterprise-technology-meetup/"`?

**Comment by webjay** [comment]
no, I pass it in as HTML:

    jsdom.env({
      html: html,
      done: callback
    });

**Comment by domenic** [comment]
You should additionally add a `url` option, so that jsdom knows how to interpret URLs inside your `html` string.

In 7.1.1, this will no longer crash, but instead the iframe will resolve to `"about:blank"` (as per spec). Just like if you'd done `<iframe src="@#?@#>%@$unresolvable URL@#@!!!">`.

**Comment by webjay** [comment]
ok, so if I give it `url` and `html` it will parse the HTML with `url` as base and not fetch from `url`?

**Comment by domenic** [comment]
Yes.

**Comment by Sebmaster** [comment]
Yes.
