### ISSUE TITLE
npm pack broken in >7.0.0

### ISSUE THREAD

**Issue by heydenberk** [tmpvar/jsdom#1283]
I did a binary search which confirmed it work up to and until 6.5.1, which makes sense given that the script referenced was added with version 7.0.

```
⚡ node -v
v4.2.1
⚡  npm install jsdom
jsdom@7.0.2 node_modules/jsdom
├── acorn-globals@1.0.9
├── webidl-conversions@2.0.0
├── xml-name-validator@2.0.1
├── browser-request@0.3.3
├── symbol-tree@3.1.3
├── abab@1.0.0
├── tough-cookie@2.2.0
├── nwmatcher@1.3.6
├── cssom@0.3.0
├── parse5@1.5.0
├── acorn@2.5.2
├── whatwg-url-compat@0.6.5 (tr46@0.0.2)
├── escodegen@1.7.0 (estraverse@1.9.3, esutils@2.0.2, esprima@1.2.5, source-map@0.2.0, optionator@0.5.0)
├── cssstyle@0.2.30
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)
└── request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.1, oauth-sign@0.8.0, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, qs@5.2.0, combined-stream@1.0.5, form-data@1.0.0-rc3, mime-types@2.1.7, bl@1.0.0, hawk@3.1.0, http-signature@0.11.0, har-validator@2.0.2)
⚡  cd node_modules/jsdom/
⚡  npm pack
> jsdom@7.0.2 prepublish ~/scratch/node_modules/jsdom
> npm run convert-idl

\
> jsdom@7.0.2 convert-idl ~/scratch/node_modules/jsdom
> node ./scripts/webidl/convert

module.js:339
    throw err;
    ^

Error: Cannot find module '~/scratch/node_modules/jsdom/scripts/webidl/convert'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "~/scratch/node_modules/.bin/npm" "run" "convert-idl"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE
npm ERR! jsdom@7.0.2 convert-idl: `node ./scripts/webidl/convert`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsdom@7.0.2 convert-idl script 'node ./scripts/webidl/convert'.
npm ERR! This is most likely a problem with the jsdom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/webidl/convert
npm ERR! You can get their info via:
npm ERR!     npm owner ls jsdom
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/scratch/node_modules/jsdom/npm-debug.log

npm ERR! addLocalDirectory Could not pack ~/scratch/node_modules/jsdom to ~/scratch/.npm/jsdom/7.0.2/package.tgz
npm ERR! addLocal Could not install ~/scratch/node_modules/jsdom
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "pack"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! jsdom@7.0.2 prepublish: `npm run convert-idl`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsdom@7.0.2 prepublish script 'npm run convert-idl'.
npm ERR! This is most likely a problem with the jsdom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run convert-idl
npm ERR! You can get their info via:
npm ERR!     npm owner ls jsdom
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/scratch/node_modules/jsdom/npm-debug.log
```

**Comment by Sebmaster** [comment]
You can't pack a `npm i`d jsdom, you should clone the github repo and pack that.
