### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by lvegerano** [tmpvar/jsdom#1294]
Running my project I get this error:

``` javascript
Uncaught Error: SyntaxError: Setter must have exactly one formal parameter.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/luisvegerano/Git/coschedule/api/node_modules/jsdom/lib/jsdom/level2/core.js:1:94)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```
I'm using node v4

**Comment by domenic** [comment]
It sounds like your JavaScript code inside the page has a SyntaxError. Can you provide a reproducible code sample?

**Comment by lvegerano** [comment]
https://gist.github.com/anonymous/46bdb7e2565341c04b50

Thanks

**Comment by domenic** [comment]
OK. Can you pare that down to the minimal number of lines necessary to re-create the error? Asking us to debug your entire program is not really going to work.

**Comment by lvegerano** [comment]
I think is need to open this issue with jquery not you guys.
