### ISSUE TITLE
Polling for AJAX data leads to cryptic timer error

### ISSUE THREAD

**Issue by rkubik** [tmpvar/jsdom#1340]
jsdom: 7.0.2
    node: 4.2.2

Code to reproduce:

```javascript
var jsdom = require("jsdom").jsdom;
var fs = require('fs');
var jquery = fs.readFileSync('./jquery.js', 'utf-8');

jsdom.env({
    url: "http://www.flysfo.com/flight-info/flight-status",
    src: [jquery],
    features: {
        FetchExternalResources : ['script', 'img', 'css', 'frame', 'iframe', 'link'],
        ProcessExternalResources : ['script']
    },
    done: function(err, window) {
        if (err) {
            console.log('Error:', err);
            return;
        }

        function getDate() {
            window.setTimeout(function () {
                var lastUpdate = window.$(".last_update").text();
                if (lastUpdate !== "  Loading ") {
                    console.log("Last update:", lastUpdate);
                    window.close();
                } else {
                    getDate();
                }
            }, 1000);
        }

        getDate();
    }
});
```

Output:

```javascript
timers.js:275
    timer._repeat.call(this);
                  ^

TypeError: timer._repeat.call is not a function
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by Sebmaster** [comment]
Ha, know why: the on-page script provides a string to setTimeout, which is not implemented in node (and we'd have to fix it to run in window anyways, but haven't yet).

**Comment by domenic** [comment]
So this dupes to #1291... we should really fix that :(
