### ISSUE TITLE
Support for SVG Elements is broken on ^8.0.0

### ISSUE THREAD

**Issue by lehni** [tmpvar/jsdom#1371]
This simple example used to work in `<8.0.0` (except for the lack of support of case-sensitivity as tracked by #620):

```js
var element = paper.document.createElementNS('http://www.w3.org/2000/svg', 'svg');
console.log(element);
console.log(require('jsdom').serializeDocument(element));
```
It used to print this:
```
Element { ... }
<svg></svg>
```
Now I get this:
```
HTMLUnknownElement {}
/Users/lehni/Development/JavaScript/jsdom/lib/jsdom/browser/documentAdapter.js:72
  return Boolean(node.tagName);
                     ^

TypeError: Cannot read property 'tagName' of null
    at Object.exports.isElementNode (/Users/lehni/Development/JavaScript/jsdom/lib/jsdom/browser/documentAdapter.js:72:22)
    at Serializer._serializeChildNodes (/Users/lehni/Development/JavaScript/jsdom/node_modules/parse5/lib/serialization/serializer.js:71:34)
    at Serializer.serialize (/Users/lehni/Development/JavaScript/jsdom/node_modules/parse5/lib/serialization/serializer.js:57:10)
    at exports.domToHtml (/Users/lehni/Development/JavaScript/jsdom/lib/jsdom/browser/domtohtml.js:15:25)
    at Object.exports.env.exports.jsdom.env.exports.serializeDocument (/Users/lehni/Development/JavaScript/jsdom/lib/jsdom.js:249:10)
    at Object.<anonymous> (/Users/lehni/Development/JavaScript/paper.js/examples/Node.js/SVGExport.js:10:30)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

This issue is stopping us from adopting `^8.0.0` in paper.js at the moment.

**Comment by domenic** [comment]
serializeDocument is not meant to work on individual elements, only on whole HTML documents. For example, the following code works with no exception:

```js
  const document = jsdom.jsdom();
  const element = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  console.log(element.outerHTML);
```

SVG will indeed be represented by HTMLUnknownElement in our implementation, since we don't have a SVG DOM, but that shouldn't cause any problems.

**Comment by lehni** [comment]
That makes a lot of sense, of course. We used to call `domToHtml(node);` and that stopped working at one point, so there was a PR to use this instead and I never questioned it: https://github.com/paperjs/paper.js/issues/821
