### ISSUE TITLE
SecurityError after updating to 8.0.0

### ISSUE THREAD

**Issue by ingro** [tmpvar/jsdom#1372]
Hello! I recentely update to 8.0.0. from 7.x and I get this error while executing my tests:

```
SecurityError
    at HistoryImpl._sharedPushAndReplaceState (D:\projects\app\node_modules\jsdom\lib\jsdom\living\window\History-impl.js:87:15)
    at HistoryImpl.replaceState (D:\projects\app\node_modules\jsdom\lib\jsdom\living\window\History-impl.js:72:10)
    at History.replaceState (D:\projects\app\node_modules\jsdom\lib\jsdom\living\generated\History.js:89:58)
    at getCurrentLocation (D:\projects\app\node_modules\react-router\node_modules\history\lib\createBrowserHistory.js:62:39)
```

I didn't change anything, looking at the stack trace it seems that the call is generated by `react-router`.

Is there something I need to do to make 8.0.0's history works?

**Comment by Sebmaster** [comment]
Do you set the `url` option when you initialize jsdom? Seems like react-router might be trying to resolve `<something>` against `about:blank` (the default), which almost never works (except if something is a hash-only url).

**Comment by domenic** [comment]
There are several `"SecurityError"`s in that file: https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/window/History-impl.js

It looks like you are indeed running into the problem @Sebmaster mentioned, on line 87.

**Comment by ingro** [comment]
Yep, that was the case, thanks for the fast reply :)
