### ISSUE TITLE
XPathResult is not defined

### ISSUE THREAD

**Issue by vsemozhetbyt** [tmpvar/jsdom#1472]
Windows 7, JSDOM 8.5.0

Test script:
```JavaScript
const jsdom = require('jsdom');

jsdom.env({url: 'https://www.w3.org/TR/xpath/', done: (err, window) => {
  console.log(window.document.querySelector('title').textContent);
  
  console.log(window.document.evaluate('.//title', window.document.documentElement,
          null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.textContent);
}});
```

Output:
```
XML Path Language (XPath)
test.js:7
          null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.textContent);
                ^
ReferenceError: XPathResult is not defined
    at Object.jsdom.env.done (test.js:7:17)
    at process.nextTick (node_modules\jsdom\lib\jsdom.js:297:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

If I replace `XPathResult.FIRST_ORDERED_NODE_TYPE` by `9` (see [xpath.js](https://github.com/tmpvar/jsdom/blob/3dfcf59f0e7945d79cb5a1b45420a993a98a29d0/lib/jsdom/level3/xpath.js#L1770)), the output is correct (however XPath in JSDOM is dramatically slow):
```
XML Path Language (XPath)
XML Path Language (XPath)
```

**Comment by domenic** [comment]
Use window.XPathResult.

**Comment by vsemozhetbyt** [comment]
Oh. Sorry. Browser habit pitfall.

By the way, should it be so slow?

```javascript
const jsdom = require('jsdom');

jsdom.env({url: 'https://www.w3.org/TR/xpath/', done: (err, window) => {
  
  let hrstart = process.hrtime();
  console.log(window.document.querySelector('title').textContent);
  let hrend = process.hrtime(hrstart);
  console.log(`${ hrend[0] }.${ Math.floor(hrend[1] / 1e6) }\n`);
  
  hrstart = process.hrtime();
  console.log(window.document.evaluate('.//title', window.document.documentElement,
          null, window.XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.textContent);
  hrend = process.hrtime(hrstart);
  console.log(`${ hrend[0] }.${ Math.floor(hrend[1] / 1e6) }\n`);
}});
```

```
XML Path Language (XPath)
0.11

XML Path Language (XPath)
10.845
```

**Comment by domenic** [comment]
It isn't optimized really. We prefer CSS selectors. Maybe one day we'll replace it though.

**Comment by vsemozhetbyt** [comment]
Thank you. Please don't abandon it. CSS selectors are not good enough for many cases, XPath is still more flexible and rich.

**Comment by vsemozhetbyt** [comment]
Maybe [this implementation](https://github.com/google/wicked-good-xpath) will be faster.

**Comment by domenic** [comment]
Yeah, it would be great to re-do our XPath implementation to reuse an existing one, but it's not at all high priority for the team. Pull requests welcome.
