### ISSUE TITLE
Fail to parse an URL and can't catch the error

### ISSUE THREAD

**Issue by zp-j** [tmpvar/jsdom#1484]
Hi there,

Excuse me I'm new here, I came across an issue that jsdom fails to parse an URL and throws out an error. I tried to use `try...catch...` but it didn't work. 

Here's the code:
```javascript
'use strict';

const fs = require("fs");
const jsdom = require("jsdom");
const jquery = fs.readFileSync("../node_modules/jquery/dist/jquery.js", "utf-8");

try {
  jsdom.env({
    url: "http://www.crownbiochina.com/%E5%85%B3%E4%BA%8E%E5%86%A0%E7%A7%91/%E5%85%AC%E5%8F%B8%E7%AE%80%E4%BB%8B/",
    src: [jquery],
    done: (err, window) => {
      if (err) {
        console.error('[JSDOM]', err, window);
      } else {
        var $ = window.$;
        console.log($('script'));
      }
    }
  });
} catch (e) {
  console.log(e);
}
```

Here's the error:
```shell
/project_path/node_modules/cssom/lib/parse.js:59
		throw error;
		^

Error: Unexpected } (line 9, char 1)
    at parseError (/project_path/node_modules/cssom/lib/parse.js:54:15)
    at Object.parse (/project_path/node_modules/cssom/lib/parse.js:329:7)
    at HTMLStyleElementImpl.evaluateStylesheet (/project_path/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:39:31)
    at HTMLStyleElementImpl._attach (/project_path/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:83:24)
    at HTMLHeadElementImpl._attach (/project_path/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:294:15)
    at HTMLHeadElementImpl._attach (/project_path/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:110:11)
    at HTMLHtmlElementImpl._attach (/project_path/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:294:15)
    at HTMLHtmlElementImpl._attach (/project_path/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:110:11)
    at DocumentImpl.insertBefore (/project_path/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:227:22)
    at DocumentImpl.appendChild (/project_path/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:334:17)
```

Did I use the API in a wrong way? Or did I miss anything? All comments and suggestions are welcomed.

Thanks in advance,
zp-j

**Comment by Joris-van-der-Wel** [comment]
I suspect this is the same issue as #1477, could you try an older version of jsdom (version 8 instead of 9)?

**Comment by zp-j** [comment]
Thanks for your help @Joris-van-der-Wel , it works after I changed back to `jsdom@8.5.0`. I will stay tuned on this issue. :D
