### ISSUE TITLE
TypeError: Cannot read property 'emit' of null,    

### ISSUE THREAD

**Issue by aggied** [tmpvar/jsdom#1507]
See the recent conversation at #1280 . 

Tried both node 4.4.0 and node 6.2.0. Spent hours on this, and I just simply can't get the app to keep running to pull down even 100 pages without this error. I am running `jsdom.env` in a loop, and need to pull down a few hundred different domains. Without fail this error will invariably occur. I've tried jar, maxSockets, etc. 

I'm on jsdom version 9.2.0 and request is at 2.72.0

thoughts? @desktoping you still experiencing this?

`````
TypeError: Cannot read property 'emit' of null,     
at Socket.connectionErrorHandler (/home/ubuntu/pullApp/node_modules/request/request.js:83:24),     
at Socket.g (events.js:286:16),     
at emitOne (events.js:101:20),     
at Socket.emit (events.js:188:7),     
at emitErrorNT (net.js:1272:8),     
at _combinedTickCallback (internal/process/next_tick.js:74:11),     
at process._tickCallback (internal/process/next_tick.js:98:9)
`````

**Comment by Sebmaster** [comment]
Seems like an upstream issue: https://github.com/request/request/issues/2226

**Comment by domenic** [comment]
Closing since there's not much we can do :(
