### ISSUE TITLE
Clipboard API

### ISSUE THREAD

**Issue by tleunen** [tmpvar/jsdom#1568]
Hi,

I don't see any implementation of the clipboard api, with the DataTransfer, DataTransferItemList and DataTransferItemListItem objects. Is there any plan supporting it?

**Comment by domenic** [comment]
A pull request adding support for this would definitely be welcome.

**Comment by christopher-schroer** [comment]
Is there any plan to support DataTransfer? It would help with an issue I'm having testing onDrop events using react-testing-library

https://github.com/kentcdodds/react-testing-library/issues/339

**Comment by 0xdevalias** [comment]
It's no full implementation to be sure.. but depending what you want out of the `DataTransfer` object, you may find good info on where to look to start implementing this/hacking around it for your needs in: https://github.com/jsdom/jsdom/issues/1272#issuecomment-486088445

**Comment by icy0307** [comment]
> It's no full implementation to be sure.. but depending what you want out of the `DataTransfer` object, you may find good info on where to look to start implementing this/hacking around it for your needs in: [#1272 (comment)](https://github.com/jsdom/jsdom/issues/1272#issuecomment-486088445)

I tried to mock ClipBoardEvent same as you did, `import { implementation } from 'jsdom/lib/jsdom/living/events/Event-impl';

// @ts-ignore
class ClipboardEventMock extends implementation implements ClipboardEvent  {
    public readonly clipboardData: DataTransfer | null;
    public constructor(type: string, eventInitDict?: ClipboardEventInit) {
        super(type, eventInitDict);
        this.clipboardData = eventInitDict?.clipboardData || null;
    }
}

Object.defineProperty(window, 'ClipboardEvent', {
    writable: true,
    value: jest.fn().mockImplementation((type, eventInitDict) => new ClipboardEventMock(type, eventInitDict)),
});
`
but got a quiet wired result `TypeError: Class constructor EventImpl cannot be invoked without 'new'
    at new ClipboardEventMock (/Users/icyflzhang/Documents/web/melo/melo-features/test/helper/ClipboardEvent.mock.ts:7:9)
    at Object.<anonymous> (/Users/icyflzhang/Documents/web/melo/melo-features/test/helper/ClipboardEvent.mock.ts:12:1)
    at Runtime._execModule (/Users/icyflzhang/Documents/web/melo/node_modules/jest-runtime/build/index.js:1217:24)
    at Runtime._loadModule (/Users/icyflzhang/Documents/web/melo/node_modules/jest-runtime/build/index.js:828:12)
    at Runtime.requireModule (/Users/icyflzhang/Documents/web/melo/node_modules/jest-runtime/build/index.js:679:10)
    at Runtime.requireModuleOrMock (/Users/icyflzhang/Documents/web/melo/node_modules/jest-runtime/build/index.js:849:21)
    at Object.<anonymous> (/Users/icyflzhang/Documents/web/melo/melo-features/test/integration/features/doc_link/doclink_copy_paste.test.ts:4:1)
    at Runtime._execModule (/Users/icyflzhang/Documents/web/melo/node_modules/jest-runtime/build/index.js:1217:24)
    at Runtime._loadModule (/Users/icyflzhang/Documents/web/melo/node_modules/jest-runtime/build/index.js:828:12)
    at Runtime.requireModule (/Users/icyflzhang/Documents/web/melo/node_modules/jest-runtime/build/index.js:679:10)
    at jasmine2 (/Users/icyflzhang/Documents/web/melo/node_modules/jest-jasmine2/build/index.js:230:13)
    at runTestInternal (/Users/icyflzhang/Documents/web/melo/node_modules/jest-runner/build/runTest.js:375:22) {stack: 'TypeError: Class constructor EventImpl cannot…_modules/jest-runner/build/runTest.js:375:22)', message: 'Class constructor EventImpl cannot be invoked without 'new''}`

**Comment by TimothyGu** [comment]
@icy0307 Instead of reaching into `jsdom/lib` which is unsupported, you should create a new mock for every window instead. Then you could say `extends window.Event`.

**Comment by clragon** [comment]
I just ran into this issue while trying to test my file type input with a drop event. 
All the workarounds seem to be insane hacks though.

**Comment by rudolfbyker** [comment]
The simplest sane workaround I can think of is to implement `ClipboardEvent` like this:

```ts
class MockClipboardEvent extends Event implements ClipboardEvent {
  clipboardData: DataTransfer | null = null;
}
```

And then at the start of every test or script, do this:

```ts
window.ClipboardEvent = MockClipboardEvent;
```

If you need to perform test assertions of otherwise manipulate the `ClipboardEvent` objects, you could wrap it in a factory that collects all instances of `MockClipboardEvent` as they are created, for later inspection. You can also add any methods you like. For example:

```ts
export interface MockClipboardEvent extends ClipboardEvent {
  // Declare any extra stuff you need for testing.
  foo(): void;
}

export function createMockClipboardEventClass() {
  const instances: MockClipboardEvent[] = [];

  class _MockClipboardEvent extends Event implements MockClipboardEvent {
    clipboardData: DataTransfer | null;

    constructor(type: string, eventInitDict?: ClipboardEventInit) {
      super(type, eventInitDict);
      this.clipboardData = null;
      instances.push(this);
    }

    // Any extra stuff you need for testing.
    foo() {
      console.log(this.clipboardData);
    }
  }

  return {
    class: _MockClipboardEvent,
    instances,
  };
}
```

Then in your tests, you can check which clipboard events were created and what they contained, and even manipulate them in flight.
