### ISSUE TITLE
include jquery and bootstrap datetimepicker in jsdom

### ISSUE THREAD

**Issue by wendy0402** [tmpvar/jsdom#1602]
Hi, guys please help me,
I use Jsdom for testing with mocha. requiring bootstrap-datetimepicker will raise an error as follows:
```
TypeError: Cannot set property 'datetimepicker' of undefined
      at app/assets/javascripts/vendor/eonasdan-bootstrap-datetimepicker/bootstrap-datetimepicker.js:2395:5
      at picker (app/assets/javascripts/vendor/eonasdan-bootstrap-datetimepicker/bootstrap-datetimepicker.js:42:26)
      at Object.<anonymous> (app/assets/javascripts/vendor/eonasdan-bootstrap-datetimepicker/bootstrap-datetimepicker.js:36:2)
      at loader (node_modules/babel-register/lib/node.js:146:5)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:156:7)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (app/assets/javascripts/components/formsy/formsy_date_time.js:5:1)
      at loader (node_modules/babel-register/lib/node.js:146:5)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:156:7)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (app/assets/javascripts/components/rule_form/rule_inputs.js:4:1)
      at loader (node_modules/babel-register/lib/node.js:146:5)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:156:7)
      at require (internal/module.js:20:19)
      at Context.<anonymous> (test/ruleFom/ruleInputs.spec.js:7:25)
```

here is my jsdom node script:
```js
import {jsdom} from 'jsdom';
var $ = require('jquery');
global.document = jsdom('<html><head></head></html>');
const win = document.defaultView;
win.jQuery = win.$ = $(win);

global.window = win;
global.jQuery = global.$ = win.jQuery;

Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    global[property] = document.defaultView[property];
  }
});

global.navigator = {
  userAgent: 'node.js'
};
```
After further investigation, I found out the reason. This is code inside bootstrap-datetimepicker:
```js
(function (factory) {
    'use strict';
    if (typeof define === 'function' && define.amd) {
        // AMD is used - Register as an anonymous module.
        define(['jquery', 'moment'], factory);
    } else if (typeof exports === 'object') {
        module.exports = factory(require('jquery'), require('moment'));
    } else {
        // Neither AMD nor CommonJS used. Use global variables.
        if (typeof jQuery === 'undefined') {
            throw 'bootstrap-datetimepicker requires jQuery to be loaded first';
        }
        if (typeof moment === 'undefined') {
            throw 'bootstrap-datetimepicker requires Moment.js to be loaded first';
        }
        factory(jQuery, moment);
    }
```

since I run jsdom in node environment, it'll go into block:
```js
else if (typeof exports === 'object') {
        module.exports = factory(require('jquery'), require('moment'));
}
```
As stated in the jquery readme. at node environment, when requiring jquery it need to add `window` as argument. However in this code it doesn't( only `require(jquery)`). can someone help me?

thank you

**Comment by domenic** [comment]
See https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global

**Comment by wendy0402** [comment]
@domenic thanks for the fast response, however I still get same errors, I update my code as follows:
```js
import React from 'react';
import { mount } from 'enzyme';
import Formsy from 'formsy-react';
import jsdom from 'jsdom';
Inputs = require('../javascripts/components/example/inputs.js');

let options = {value: 'test', description: 'bar'},
jsdom.env({
        html: "",
        scripts: [myLibrary],
        done(err, window) {
          Inputs = require('../../app/assets/javascripts/components/rule_form/rule_inputs.js');
          const wrapper = mount(
            <Formsy.Form>
              <Inputs options={options} />
            </Formsy.Form>
          );
          console.log(wrapper.find("[name='paymentType']").props())
          done()
        }
     });
```

I need to get Inputs(this is where bootstrap datetimepicker imported) that's why I put inputs insed done block

**Comment by domenic** [comment]
Right, but as shown in that page, you can't use require to require such things. You need to insert them with a script element (like the myLibrary variable, which is undefined in your example).

Another issue is that you're using JSX syntax, which is not supported in jsdom or Node.js.
