### ISSUE TITLE
Expecting a function in instanceof check, but got undefined

### ISSUE THREAD

**Issue by giedrius-timinskis** [tmpvar/jsdom#1620]
Hey all,

I've been getting this error:

```
/node_modules/jsdom/lib/jsdom/living/generated/EventInit.js:32
    if (obj instanceof Date || obj instanceof RegExp) {
                       ^
TypeError: Expecting a function in instanceof check, but got undefined
    at Object.convert (/Users/client/Development/7tennis-web/node_modules/jsdom/lib/jsdom/living/generated/EventInit.js:32:24)
    at new EventImpl (/Users/client/Development/7tennis-web/node_modules/jsdom/lib/jsdom/living/events/Event-impl.js:8:48)
    at Object.setup (/Users/client/Development/7tennis-web/node_modules/jsdom/lib/jsdom/living/generated/Event.js:199:17)
    at Object.create (/Users/client/Development/7tennis-web/node_modules/jsdom/lib/jsdom/living/generated/Event.js:183:10)
    at HTMLDocument.core.Document.createEvent (/Users/client/Development/7tennis-web/node_modules/jsdom/lib/jsdom/level2/events.js:156:16)
    at Window.process.nextTick (/Users/client/Development/7tennis-web/node_modules/jsdom/lib/jsdom/browser/Window.js:376:34)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

This seems to happen during the .jsdom() call. I'm using Jest, Enzyme and sinon.

Here's the file structure:

```
import React from 'react';
import { shallow, mount } from 'enzyme';
import { MoreDropdown } from '../MoreDropdown';

// https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md
var jsdom = require('jsdom').jsdom;

global.document = jsdom('');
global.window = document.defaultView;
Object.keys(document.defaultView).forEach((property) => {
  if (typeof global[property] === 'undefined') {
    global[property] = document.defaultView[property];
  }
});

global.navigator = {
  userAgent: 'node.js'
};

const sinon = require('sinon');
```

^^^ that seems to fail before it reaches any tests.

Note: I don't get the 

```
if (obj instanceof Date || obj instanceof RegExp) 
                       ^
```

if I import sinon before jsdom, but `Expecting a function in instanceof check, but got undefined` error is still shown.

Please let me know if you have any tips on solving this.
Cheers!

**Comment by domenic** [comment]
This seems to be a consequence of the unsupported practice of mashing together two different global objects; see https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global.
