### ISSUE TITLE
Cant load image through Canvas.Image

### ISSUE THREAD

**Issue by gnepud** [tmpvar/jsdom#1632]
Hello,

I'm attempting to load a image by `Canvas.Image` using the following piece of code:

index.js
```
var fs = require('fs');
var jsdom = require('jsdom');
var Canvas = require('canvas');

var imgSrc  = fs.readFileSync('./test_img.js', 'utf-8');

var html = '<html><body></body></html>';

var virtualConsole = jsdom.createVirtualConsole();
virtualConsole.on('log', (message) => {
    console.log('console.log called ->', message);
});
virtualConsole.on('jsdomError', (message) => {
    console.error('Error ->', message);
});

jsdom.env({
    html: html,
    src: [imgSrc],
    features: { FetchExternalResources: ['img'] },

    virtualConsole: virtualConsole,

    done: function(err, window) {
      
    }
});
```
test_img.js
```
var webpImgTest = new Image();
webpImgTest.onload = function () {
    console.log('ok');
};
webpImgTest.src = 'data:image/webp;base64,UklGRh4AAABXRUJQVlA4TBEAAAAvAQAAAAfQ//73v/+BiOh/AAA=';
```
I have the following error 
```
Error -> { Error: Could not load img: "data:image/webp;base64,UklGRh4AAABXRUJQVlA4TBEAAAAvAQAAAAfQ//73v/+BiOh/AAA="
    at e (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:44:23)
    at Object.check (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:85:11)
    at Object.check (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:88:23)
    at /Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:104:12
    at HTMLScriptElementImpl._attach (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:42:72)
    at HTMLHtmlElementImpl.insertBefore (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:222:22)
    at HTMLHtmlElementImpl.appendChild (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:329:17)
    at HTMLHtmlElement.appendChild (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/generated/Node.js:132:57)
    at processHTML (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom.js:352:39)
    at Object.exports.env.exports.jsdom.env [as env] (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom.js:203:5)
  detail:
   Error: Error: error while reading from input stream
       at HTMLImageElementImpl.resourceLoader.load (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/nodes/HTMLImageElement-impl.js:30:19)
       at e (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22)
       at Object.check (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:85:11)
       at Object.check (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:88:23)
       at /Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:104:12
       at HTMLScriptElementImpl._attach (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:42:72)
       at HTMLHtmlElementImpl.insertBefore (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:222:22)
       at HTMLHtmlElementImpl.appendChild (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:329:17)
       at HTMLHtmlElement.appendChild (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom/living/generated/Node.js:132:57)
       at processHTML (/Users/peng/www/plotly/node_modules/jsdom/lib/jsdom.js:352:39),
  type: 'resource loading' }
```
Version:
jsdom: 9.8.0
node-canvas: 1.6.0
node: 6.9.0

Are there any ideas? Thank you.

**Comment by domenic** [comment]
I'm not sure we support data URLs for images, and I'm certain we don't support webp.

**Comment by gnepud** [comment]
@domenic I tried with an image png by data URLs. it is functioned. But not webp and svg+xml.
Have you any plan for support webp and svg ?

**Comment by domenic** [comment]
That would be up to the authors of the canvas npm package; we depend on them for any image decoding.

**Comment by gnepud** [comment]
@domenic thx. i understood.
