### ISSUE TITLE
breaking change in 9.8.2

### ISSUE THREAD

**Issue by madole** [tmpvar/jsdom#1635]
`SyntaxError: Invalid flags supplied to RegExp constructor 'u'`

Not sure what this is coming from but it's definitely a breaking change.

**Comment by Sebmaster** [comment]
That's a node error and not something we can do anything about.

**Comment by Sebmaster** [comment]
Oh, is the trace in jsdom itself?

**Comment by naegelyd** [comment]
In following the traceback, it appears the issue arises in [this line](https://github.com/tmpvar/jsdom/blob/6bc9e23e1fe9ad4b8ce753579dfe3731d3fb2eb4/lib/jsdom/living/helpers/ordered-set-parser.js#L4).

**Comment by joseluisq** [comment]
Tested in Node `v4` and `v5`.
```sh
> tape -r babel-register test/test.js
/home/travis/build/joseluisq/slendr/node_modules/jsdom/lib/jsdom/living/helpers/ordered-set-parser.js:4
  return new Set(input.split(/[\u{0009}\u{000A}\u{000C}\u{000D}\u{0020}]+/u).filter(Boolean));
                      ^
SyntaxError: Invalid flags supplied to RegExp constructor 'u'
    at new RegExp (native)
    at orderedSetParser (/home/travis/build/joseluisq/slendr/node_modules/jsdom/lib/jsdom/living/helpers/ordered-set-parser.js:4:23)
    at Object.resetDOMTokenList [as reset] (/home/travis/build/joseluisq/slendr/node_modules/jsdom/lib/jsdom/living/dom-token-list.js:187:25)
    at createDOMTokenList (/home/travis/build/joseluisq/slendr/node_modules/jsdom/lib/jsdom/living/dom-token-list.js:202:11)
    at HTMLDivElementImpl.classList (/home/travis/build/joseluisq/slendr/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:297:25)
    at HTMLDivElementImpl._attrModified (/home/travis/build/joseluisq/slendr/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:205:29)
    at HTMLDivElementImpl._attrModified (/home/travis/build/joseluisq/slendr/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:117:25)
    at Object.exports.hasAttributeByNameNS.exports.appendAttribute (/home/travis/build/joseluisq/slendr/node_modules/jsdom/lib/jsdom/living/attributes.js:204:11)
    at Object.exports.hasAttributeByNameNS.exports.setAttributeValue (/home/travis/build/joseluisq/slendr/node_modules/jsdom/lib/jsdom/living/attributes.js:379:13)
    at /home/travis/build/joseluisq/slendr/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:273:18
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
Done. Your build exited with 1.
```

With Node v6 it works.

**Comment by emmenko** [comment]
I'm getting the same error. With `9.8.1` it works, so this has been introduced in `9.8.2`.
Thanks for the help!

**Comment by bySabi** [comment]
Same here!, is broken on `4` and `5`, it works on `6`

**Comment by Sebmaster** [comment]
Working on it, will be fixed in a few minutes.

**Comment by Sebmaster** [comment]
Should be fixed by 218c8f70ba3d5f8c99f20631d203ac5ac0082e28 and published 9.8.3 to npm.

**Comment by pokidovea** [comment]
Good job. Now it works for me

**Comment by bySabi** [comment]
Here is working again.
Thanks
