### ISSUE TITLE
[bug] defineProperty don't protect overwriting on window emmulation

### ISSUE THREAD

**Issue by GammaNu** [tmpvar/jsdom#1653]
defineProperty dont protect overwriting on test environnement window emmulation but work in chrome and firefox.
just do :
``` 
git clone https://github.com/GammaNu/jest-defineProperty-window-bug
cd jest-defineProperty-window-bug
npm install
npm test
```
it should pass.

why jest stuff ? https://github.com/facebook/jest/issues/2084#issuecomment-260264470

here is what i get with --debug on Windows 7 64bit
```
$ npm --version
3.8.6
$ node --version
v6.1.0
$ npm test

> @ test C:\Users\GammaNu\Documents\GitHub\jest-defineProperty-window-bug
> jest --debug

jest version = 17.0.1
test framework = jasmine2
config = {
  "rootDir": "C:\\Users\\GammaNu\\Documents\\GitHub\\jest-defineProperty-window-bug",
  "name": "C:-Users-GammaNu-Documents-GitHub-jest-defineProperty-window-bug",
  "setupFiles": [],
  "testRunner": "C:\\Users\\GammaNu\\Documents\\GitHub\\jest-defineProperty-window-bug\\node_modules\\jest-jasmine2\\build\\index.js",
  "transform": [
    [
      "^.+\\.jsx?$",
      "C:\\Users\\GammaNu\\Documents\\GitHub\\jest-defineProperty-window-bug\\node_modules\\babel-jest\\build\\index.js"
    ]
  ],
  "usesBabelJest": true,
  "automock": false,
  "bail": false,
  "browser": false,
  "cacheDirectory": "C:\\Users\\GammaNu\\AppData\\Local\\Temp\\jest",
  "coveragePathIgnorePatterns": [
    "\\\\node_modules\\\\"
  ],
  "coverageReporters": [
    "json",
    "text",
    "lcov",
    "clover"
  ],
  "expand": false,
  "globals": {},
  "haste": {
    "providesModuleNodeModules": []
  },
  "mocksPattern": "__mocks__",
  "moduleDirectories": [
    "node_modules"
  ],
  "moduleFileExtensions": [
    "js",
    "json",
    "jsx",
    "node"
  ],
  "moduleNameMapper": {},
  "modulePathIgnorePatterns": [],
  "noStackTrace": false,
  "notify": false,
  "preset": null,
  "resetMocks": false,
  "resetModules": false,
  "snapshotSerializers": [],
  "testEnvironment": "jest-environment-jsdom",
  "testPathDirs": [
    "C:\\Users\\GammaNu\\Documents\\GitHub\\jest-defineProperty-window-bug"
  ],
  "testPathIgnorePatterns": [
    "\\\\node_modules\\\\"
  ],
  "testRegex": "(/__tests__/.*|\\.(test|spec))\\.jsx?$",
  "testURL": "about:blank",
  "timers": "real",
  "transformIgnorePatterns": [
    "\\\\node_modules\\\\"
  ],
  "useStderr": false,
  "verbose": null,
  "watch": false,
  "cache": true,
  "watchman": true,
  "testcheckOptions": {
    "times": 100,
    "maxSize": 200
  }
}
 FAIL  .\savage-overwrite.test.js
  ● unOverwritableGlobalConst

    expect(received).toEqual(expected)

    Expected value to equal:
      {"do": "me"}
    Received:
      "osef"

    Difference:

    Comparing two different types of values:
      Expected: object
      Received: string

      at Object.obj (savage-overwrite.test.js:11:16)
      at process._tickCallback (internal\process\next_tick.js:103:7)

  ● unOverwritableGlobalConst in strict mode

    expect(received).toEqual(expected)

    Expected value to equal:
      {"do": "me"}
    Received:
      "osef"

    Difference:

    Comparing two different types of values:
      Expected: object
      Received: string

      at Object.obj (savage-overwrite.test.js:22:16)
      at process._tickCallback (internal\process\next_tick.js:103:7)

  × unOverwritableGlobalConst (5ms)
  × unOverwritableGlobalConst in strict mode (1ms)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        1.24s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

```

**Comment by i8-pi** [comment]
I think this is a node bug https://github.com/nodejs/node/issues/10223

**Comment by domenic** [comment]
This is probably a Node bug, but this example is using third-party libraries, and we can't help debug that. If you can produce a minimal repro, like the new issue template asks for, then we can reopen this to track any Node bug in progress.
