### ISSUE TITLE
iframe element with src="javascript:'<html></html>'"

### ISSUE THREAD

**Issue by AlexzAK** [tmpvar/jsdom#1686]
if I load html document containing 
```
 <iframe ... src="javascript:'<html></html>'">
 </iframe>
```

jsdom fails with error
```
     Uncaught TypeError: contentWindow.eval is not a function
      at loadFrame (node_modules/jsdom/lib/jsdom/living/nodes/HTMLFrameElement-impl.js:75:19)
      at HTMLIFrameElementImpl._attach (node_modules/jsdom/lib/jsdom/living/nodes/HTMLFrameElement-impl.js:149:7)
      at HTMLDivElementImpl._attach (node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:294:15)
      at HTMLDivElementImpl._attach (node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:110:11)
      at HTMLDivElementImpl._attach (node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:294:15)
      at HTMLDivElementImpl._attach (node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:110:11)
      at HTMLDivElementImpl._attach (node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:294:15)
      at HTMLDivElementImpl._attach (node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:110:11)
      at HTMLBodyElementImpl._attach (node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:294:15)
      at HTMLBodyElementImpl._attach (node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:110:11)
      at HTMLHtmlElementImpl._attach (node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:294:15)
      at HTMLHtmlElementImpl._attach (node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:110:11)
      at DocumentImpl.insertBefore (node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:227:22)
      at DocumentImpl.appendChild (node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:334:17)
      at DocumentImpl.appendChild (node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:399:18)
      at setChild (node_modules/jsdom/lib/jsdom/browser/htmltodom.js:288:18)
      at HtmlToDom._parseWithparse5v1 (node_modules/jsdom/lib/jsdom/browser/htmltodom.js:90:7)
      at HtmlToDom.appendHtmlToDocument (node_modules/jsdom/lib/jsdom/browser/htmltodom.js:47:48)
      at setInnerHTML (node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:70:27)
      at DocumentImpl.write (node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:452:7)
      at Document.write (node_modules/jsdom/lib/jsdom/living/generated/Document.js:351:27)
      at Object.exports.jsdom (node_modules/jsdom/lib/jsdom.js:144:21)
      at processHTML (node_modules/jsdom/lib/jsdom.js:297:26)
      at resourceLoader.readFile (node_modules/jsdom/lib/jsdom.js:200:7)
      at ReadStream.readableStream.on (node_modules/jsdom/lib/jsdom/browser/resource-loader.js:76:7)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by snuggs** [comment]
@AlexzAK I'll take a look at it after Christmas. 

Curious why the need for `src="javascript:'<html></html>'`. Could potentially be the issue.
What happens when not evaluating JS with the `javascript:` protocol.

**Comment by AlexzAK** [comment]
@snuggs thanks, it is not a big problem, since I have workaround
But that html causes jsdom to fall, so it is a bug

I really don't understand why my target website uses `src="javascript:'<html></html>'` actually.
But I scraping it and have no control over it's code.

Same issue with
```
const {jsdom} = require('jsdom');
require("jsdom").defaultDocumentFeatures = {
  FetchExternalResources: false,
  ProcessExternalResources: false,
  SkipExternalResources: true
};
```

Not sure that I understand docs right. As far as I see, that config should disable JS

**Comment by manishwaran** [comment]
+1

**Comment by domenic** [comment]
https://twitter.com/slicknet/status/782274190451671040

**Comment by domenic** [comment]
This should be fixed by https://github.com/tmpvar/jsdom/commit/4b503205ec664e34a0345f25f6a21ec06d373fb4, which will be released shortly.

**Comment by snuggs** [comment]
Thanks @domenic 🙏
