### ISSUE TITLE
node 6.9.0 + meteor 1.3.2.2 returns error: jsdom 7.x onward only works on Node.js 4 or newer

### ISSUE THREAD

**Issue by hems** [tmpvar/jsdom#1697]
I'm trying to install jsdom on a meteor.js application.

Switched to node 6.9.0 ( using nvm ) while running meteor 1.3.2.2, deleted my node_modules, did a fresh npm install

````
W20170103-02:43:25.785(0)? (STDERR) /Volumes/backpack/git/lamashtu/flibbr/skanner/app/.meteor/local/build/programs/server/packages/modules.js:104346
W20170103-02:43:25.787(0)? (STDERR) () => `jsdom 7.x onward only works on Node.js 4 or newer: https://github.com/t
W20170103-02:43:25.788(0)? (STDERR)  ^
W20170103-02:43:25.792(0)? (STDERR) SyntaxError: Unexpected token )
W20170103-02:43:25.792(0)? (STDERR)     at /Volumes/backpack/git/lamashtu/flibbr/skanner/app/.meteor/local/build/programs/server/boot.js:278:30
W20170103-02:43:25.792(0)? (STDERR)     at Array.forEach (native)
W20170103-02:43:25.792(0)? (STDERR)     at Function._.each._.forEach (/Users/h/.meteor/packages/meteor-tool/.1.3.2_2.1hky70u++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170103-02:43:25.792(0)? (STDERR)     at /Volumes/backpack/git/lamashtu/flibbr/skanner/app/.meteor/local/build/programs/server/boot.js:133:5
````

And the following error which seems to be less important:
````
Unable to resolve some modules:

  "canvas" in /Volumes/backpack/git/lamashtu/flibbr/skanner/app/node_modules/jsdom/lib/jsdom/utils.js (os.osx.x86_64)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save canvas
````

**Comment by Joris-van-der-Wel** [comment]
If I recall correctly, meteor embeds its own node.js binary. `nvm` has no effect. So you will have to update meteor.

**Comment by hems** [comment]
yeah that's what i thought as well
