### ISSUE TITLE
With the release 9.10.0 element.offsetWidth returns undefined

### ISSUE THREAD

**Issue by natrixnatrix89** [tmpvar/jsdom#1728]
Probably this is intended behaviour.

However regarding unit tests - upgrading to 9.10.0 triggered some failing tests.
An example
```javascript
elementA.scrollLeft = elementB.offsetWidth - elementA.offsetWidth;
```
will cause a `TypeError: Argument is NaN` because subtracting `undefined` from `undefined` yields `NaN`.

**Comment by yefremov** [comment]
Here is the code to reproduce:

```js
var jsdom = require("jsdom").jsdom;
var window = jsdom().defaultView;

var elementA = window.document.createElement("div");
var elementB = window.document.createElement("div");

window.document.body.appendChild(elementA);
window.document.body.appendChild(elementB);

elementA.scrollLeft = elementB.offsetWidth - elementA.offsetWidth;

console.log(window);
```

will throw following:

```
        throw new TypeError("Argument is NaN");
        ^

TypeError: Argument is NaN
    at Object.conversions.unrestricted double (/Users/noob/Projects/233ccca46dbbf2c34ab7104d1c211b7a/node_modules/webidl-conversions/lib/index.js:110:15)
    at HTMLDivElement.set [as scrollLeft] (/Users/noob/Projects/233ccca46dbbf2c34ab7104d1c211b7a/node_modules/jsdom/lib/jsdom/living/generated/Element.js:508:43)
    at Object.<anonymous> (/Users/noob/Projects/233ccca46dbbf2c34ab7104d1c211b7a/jsdom-issue-1728.js:14:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

Checkout this [gist](https://gist.github.com/yefremov/233ccca46dbbf2c34ab7104d1c211b7a).

**Comment by domenic** [comment]
I guess what happened is that in 9.10.0 we added no-op setters for scrollLeft and friends.

Regardless, it seems like the correct route to fixing this is to do the same thing https://github.com/tmpvar/jsdom/pull/1712 did and start returning 0 for all the offset properties. A PR similar to that one would be welcome.

**Comment by domenic** [comment]
Actually, this is a bug in [webidl-conversions](https://github.com/jsdom/webidl-conversions). [Per spec](https://heycam.github.io/webidl/#es-unrestricted-double) NaN is supposed to work, not cause an error. A PR there would also be great.

**Comment by yefremov** [comment]
Yep, but offset getter should still return `0` instead of `undefined`, tho.

**Comment by domenic** [comment]
Yeah, both things need fixing, ideally.

**Comment by yefremov** [comment]
Ok, I'll try!

**Comment by aamir-afridi-JG** [comment]
Any idea when will this get fixed?

**Comment by domenic** [comment]
When I have a free weekend to work on jsdom.
