### ISSUE TITLE
Throws on Element.prototype.matches call with pseudo-element selector

### ISSUE THREAD

**Issue by Munter** [tmpvar/jsdom#1832]
### Basic info:

- **Node.js version:** 6.9.1
- **jsdom version:** 10.0.0 (also present in 9.x)

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const dom = new JSDOM(`
  <p>text</p>
`);

dom.window.document.body.firstChild.matches('p:after');
```

Throws:
```
SyntaxError
    at HTMLParagraphElementImpl.<anonymous> (/Users/munter/git/assetgraph/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:514:11)
    at HTMLParagraphElementImpl.<anonymous> (/Users/munter/git/assetgraph/node_modules/jsdom/lib/jsdom/utils.js:113:45)
    at HTMLParagraphElement.matches (/Users/munter/git/assetgraph/node_modules/jsdom/lib/jsdom/living/generated/Element.js:278:29)
    at repl:1:37
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
```

### How does similar code behave in browsers?

Returns `true` or `false`

**Comment by domenic** [comment]
Well, this is not very valid code, since pseudo-elements aren't really selectors, even though they have legacy aliases with `:`. But I guess if it works in browsers, then probably we need to support it (and just always return false?)

/cc @dperini. The spec seems to support this, as pseudo-element selectors are part of the grammar at https://drafts.csswg.org/selectors-4/#grammar.

**Comment by dperini** [comment]
@domenic / @Munter
I will give a look and see what can be done for the `:after` and `:before` pseudo-elements asap.

Currently "nwmatcher" aims to support the W3C "Selectors Level 3" recommendation which already includes the `::after`, `::before`, `::first-line` and `::first-letter` pseudo-elements.

The decision to skip support for these selectors, at that time (2011), was due to the fact that these elements correspond to dynamically generated contents which does not exists in the source of the document.

The reasoning was that with those kind of selectors,  a call to the `select` method will always return `empty array` (0 elements) and a call to the `match` method will always return `false`.

However I fully understand the need to avoid throwing errors during the parsing of legal CSS syntax. I also suggest to try using the VERBOSITY configuration flag of "nwmatcher" to mute these kind of errors and see if that could help while support is being added.

Also the W3C "Selectors Level 4" is still a working draft (WD) but I will eventually try to support it in future versions of "nwmatcher", I just need to find more spare time to allocate to that task.

**Comment by dperini** [comment]
@Munter could you please check commit https://github.com/dperini/nwmatcher/commit/d02f63021a and tell if this fixes your issue ?

I have added parsing and validation of the following pseudo-elements: `::after`, `::before`, `::first-letter`, `::first-line`, `::selection`, `::backdrop` and `::placeholder`.

For these pseudo-element selectors the `select()` method will always return an empty nodelist (array) and the `match` method will always return false.

Notice that the single colon variants `:after`, `:before`, `:first-letter`, `:first-line` are accepted as valid while for the remaining pseudo-elements `::selection`, `::backdrop` and `::placeholder` the double colon prefix is required. This is too mimic as close as possible current browsers implementations and related specifications.
/cc @domenic

**Comment by dperini** [comment]
@Munter 
the requested fix is part of the new nwmatcher 1.4.0 hope it solves your issues.

**Comment by Munter** [comment]
@dperini Luckily I needed to handle pseudo-elements differently in my code anyway, so I have a workaround in place. When I pick up the project again soon I'll try and remove the workaround and see if it works. Thanks for the quick response on this somewhat unlikely case :)

**Comment by domenic** [comment]
This appeared to be fixed, although my attempts to add tests for it in #2243 are blocked by a combination of https://github.com/web-platform-tests/wpt/issues/11212 and jsdom's inability to enable test files that are mostly-passing.
