### ISSUE TITLE
Parsing a webpage with a body with an onload causes the error "sandbox argument must have been converted to a context."

### ISSUE THREAD

**Issue by DoomTay** [tmpvar/jsdom#1848]
### Basic info:

- **Node.js version:** v6.10.0
- **jsdom version:** 10.1.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM("<html><body onload=\"foobar()\"><p>It works</p></body></html>");

console.log(dom.window.document.body.textContent);
```
Running that code will result in the following

```node
It works
Error: Uncaught [TypeError: sandbox argument must have been converted to a context.]
    at reportException (E:\Projects\Janus Scraper\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:58:24)
    at invokeEventListeners (E:\Projects\Janus Scraper\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:236:9)
    at invokeInlineListeners (E:\Projects\Janus Scraper\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:167:7)
    at EventTargetImpl._dispatch (E:\Projects\Janus Scraper\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:122:7)
    at EventTargetImpl.dispatchEvent (E:\Projects\Janus Scraper\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:87:17)
    at Window.dispatchEvent (E:\Projects\Janus Scraper\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:64:21)
    at Window.process.nextTick (E:\Projects\Janus Scraper\node_modules\jsdom\lib\jsdom\browser\Window.js:494:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11) TypeError: sandbox argument must have been converted to a context.
    at TypeError (native)
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at Object.exports.runInContext (vm.js:67:17)
    at Window.self.(anonymous function) [as onload] (E:\Projects\Janus Scraper\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:186:25)
    at callback.(anonymous function) (E:\Projects\Janus Scraper\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:290:32)
    at invokeEventListeners (E:\Projects\Janus Scraper\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:220:27)
    at invokeInlineListeners (E:\Projects\Janus Scraper\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:167:7)
    at EventTargetImpl._dispatch (E:\Projects\Janus Scraper\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:122:7)
    at EventTargetImpl.dispatchEvent (E:\Projects\Janus Scraper\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:87:17)
    at Window.dispatchEvent (E:\Projects\Janus Scraper\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:64:21)
```

Curiously, running similar code based on the old API works just fine

```js
const oldJSD = require("jsdom/lib/old-api.js");

oldJSD.env("<html><body onload=\"foobar()\"><p>It works</p></body></html>",function(err,window)
{
	console.log(window.document.body.textContent);
})
```

### How does similar code behave in browsers?

The browser will continue as normal

**Comment by domenic** [comment]
Great catch; thank you. Will try to fix ASAP...
