### ISSUE TITLE
Can't load external css

### ISSUE THREAD

**Issue by dwqs** [tmpvar/jsdom#1927]
### Basic info:

- **Node.js version:**  v8.1.3
- **jsdom version:**  v11.1.0

### Minimal reproduction case

```js
let jsdom = require('jsdom');
const JSDOM = jsdom.JSDOM;

const domString = `
    <!DOCTYPE html>
    <html>
        <head>
            <title>Test</title>
            <link rel="stylesheet" href="./test.css">
        </head>
        <body>
            <p class="test">test content</p>
        </body>
    </html>
`;
const dom = new JSDOM(domString, {
    resources: 'usable'
});
const window = dom.window;
const document = window.document;
let color = window.getComputedStyle(document.querySelector('p'), null).getPropertyValue('color');

console.log(document.querySelector('p').textContent);  // test content
console.log('p\'s color', color);  // empty
```
When run `node test/index.js`  in terminal, the second output is empty. My directory hierarchy as follows: 

```
-test
  -- index.js
  -- test.css
```

I just write a simple rule in `test.css`:

```
.test{
    color: red
}
```
I've trawled the documentation and tried lots of variations but nothing works.

**Comment by domenic** [comment]
Like in browsers, CSS takes some time to load. You need to wait for the load event on window.

**Comment by dwqs** [comment]
Listen to the `onModulesLoaded` event on `window` ？

**Comment by dwqs** [comment]
Dose jsdom support pseudo-element ?

```
let jsdom = require('jsdom');
const JSDOM = jsdom.JSDOM;

const domString = `
    <!DOCTYPE html>
    <html>
        <head>
            <title>Test</title>
            <style>
                   .test{
                    color: red;
                    width: 50px;
                    height: 100px;
                }
                .test::before{
                    position: absolute;
                    content: 'sdas',
                    width: 20px;
                    height: 20px;
                }
                .test::after{
                    position: absolute;
                    content: 'sdas',
                    width: 40px;
                    height: 40px;
                }
           </style>
        </head>
        <body>
            <p class="test">test content</p>
        </body>
    </html>
`;
const dom = new JSDOM(domString);
const window = dom.window;
const document = window.document;
const p = document.querySelector('.test');

console.log('after', window.getComputedStyle(p, '::after').width);  // get 50px but expected 40px
console.log('before', window.getComputedStyle(p, '::before').width);  // get 50px but expected 20px
```

**Comment by domenic** [comment]
I've never heard of the onModulesLoaded event, so no, not that. The normal load event on window.

As for pseudo-elements, that sounds like a separate issue, not related to this one, so I won't talk about it in this thread.

**Comment by dwqs** [comment]
I find the `onModulesLoaded` in [Asynchronous script loading](https://github.com/tmpvar/jsdom#asynchronous-script-loading).  I maybe understand some wrong about the document.

As for pseudo-elements, I am sorry and I will open another issue [here](https://github.com/tmpvar/jsdom/issues/1928).

**Comment by domenic** [comment]
Ah OK. No, that's not an event, that's a function you define as in the example ("Inside the HTML you supply to jsdom").

You need to use the usual `window.addEventListener("load", ...)` pattern to wait for the stylesheets to load.

**Comment by dwqs** [comment]
I change my code as follows:

```js
window.addEventListener('load', () => {
    let color = window.getComputedStyle(document.querySelector('p'), null).getPropertyValue('color');

    console.log(document.querySelector('p').textContent);  
    console.log('p\'s color', color);
}, false);
```
And I get the same result above.

**Comment by domenic** [comment]
Thanks! We will look into it.

**Comment by Zirro** [comment]
It decides to not load the stylesheet [here](https://github.com/tmpvar/jsdom/blob/84861f7fe176da067e9b57f97498cc5b27d0cf83/lib/jsdom/living/nodes/HTMLLinkElement-impl.js#L56) as `whatwg-url` returns a failure for the relative path.

Replacing the relative path `./test.css` with an absolute `file://` URL will work, as well as providing an absolute `file://` URL in the JSDOM constructor's `url` option. Since there's a note about this in the README, I believe this is expected behaviour.

**Comment by dwqs** [comment]
@Zirro My system is macOS 10.12.6.  I pass the absolute path to `url` option, it's not working and get an error:

```
/Users/pomy/git/tiny-dom-helpers/node_modules/whatwg-url/lib/URL-impl.js:21
      throw new TypeError("Invalid URL");
      ^

TypeError: Invalid URL
    at new URLImpl (/Users/pomy/git/test/node_modules/whatwg-url/lib/URL-impl.js:21:13)
    at Object.setup (/Users/pomy/git/test/node_modules/whatwg-url/lib/URL.js:241:14)
    at new URL (/Users/pomy/git/test/node_modules/whatwg-url/lib/URL.js:26:9)
    at transformOptions (/Users/pomy/git/test/node_modules/jsdom/lib/api.js:267:38)
    at new JSDOM (/Users/pomy/git/test/node_modules/jsdom/lib/api.js:40:15)
```

The code as follows: 
```
// ...

const dom = new JSDOM(domString, {
    resources: 'usable',
    url: '/Users/pomy/git/test/test.css'
});

// ...
```

**Comment by Zirro** [comment]
@dwqs The constructor option should contain a path to the directory, rather than the file itself. You also need the `file://`-scheme. Try this: `file:///Users/pomy/git/test/`

**Comment by dwqs** [comment]
@Zirro It works !!! but it should be noted that the path passed to `url` option must end with '/', otherwise will get an error as follows:
```
Error: Could not load link: "file:///Users/pomy/test/test.css"
    at /Users/pomy/git/tiny-dom-helpers/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:44:23
    at Object.check (/Users/pomy/git/test/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:91:11)
    at ReadStream.<anonymous> (/Users/pomy/git/test/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:110:12)
    at ReadStream.wrappedEnqueued (/Users/pomy/git/test/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at emitOne (events.js:115:13)
```
My finally code be as follows:
```
// ...
const dom = new JSDOM(domString, {
    resources: 'usable',
    url: 'file:///Users/pomy/git/test/'
});
const window = dom.window;
const document = window.document;

window.addEventListener('load', () => {
    let color = window.getComputedStyle(document.querySelector('p'), null).getPropertyValue('color');

    console.log(document.querySelector('p').textContent);  // test content
    console.log('p\'s color', color); // red
}, false);
```
Could I close this issue? @domenic

**Comment by domenic** [comment]
I'd like to investigate why you weren't getting any console errors when we weren't able to resolve the style URL, so let me leave this open for that purpose :)

**Comment by dwqs** [comment]
OK.

**Comment by Ustimov** [comment]
FYI, I just figured out that you can use relative paths like this:
`<link rel="stylesheet" href="file://style.min.css">`.

**Comment by Ustimov** [comment]
@jokyspy hi, try this sample:
```javascript
// index.js
const jsdom = require('jsdom');
const { JSDOM } = jsdom;
const path = require('path');

const absolutePath = path.join(__dirname, 'style.css');
const { window } = new JSDOM(
    `
    <html>
    <head>
        <link rel="stylesheet" href="file://${absolutePath}">.    
    </head>
    <body></body>
    </html>
    `, {
        resources: 'usable'
    }
);

window.onload = function () {
    console.log('Body background color: ' + window.getComputedStyle(window.document.body).backgroundColor);
};

setTimeout(() => {}, 1000);
```
```css
/* style.css */
body {
    background: red;
}
```
```
node index.js
Body background color: red
```

The files shound be in the same folder.

**Comment by jrpool** [comment]
I can make jsdom load a stylesheet by prefixing the relative path with "file://". But then a browser fails to find the stylesheet. If I don't use "file://", the browser finds it but jsdom does not. I'm using jsdom 14.0.0.

**Comment by marco-souza** [comment]
Hey guys, It's finally working for me! 😁

Check this PR: https://github.com/podcodar/exercises/pull/1
