### ISSUE TITLE
ReferenceError: PostAffTracker is not defined

### ISSUE THREAD

**Issue by Pomax** [tmpvar/jsdom#1942]
Running node 8 + jsdom 11.1.0 with the following code:
```
const jsdom = require('jsdom');
const JSDOM = jsdom.JSDOM;

const options = {
  runScripts: 'dangerously',
  cookieJar: new jsdom.CookieJar()
};

function checkUserEmail(dom) {
  var document = dom.window.document;
  var email = document.getElementById('user_email');
  if (!email) {
    return setTimeout(() => checkUserEmail(dom), 500);
  }
  console.log(email);
}

JSDOM
.fromURL("https://www.pluginboutique.com/users/login", options)
.then(checkUserEmail)
```
And running this generates a rather interesting strack trace:
```
c:\Users\Pomax\Documents\git\temp\pluginboutique>node test
Error: Uncaught [ReferenceError: PostAffTracker is not defined]
    at reportException (J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:63:24)
    at processJavaScript (J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:130:7)
    at HTMLScriptElementImpl._eval (J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:65:7)
    at J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:31:22
    at Object.check (J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:91:11)
    at J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:110:12
    at HTMLScriptElementImpl._attach (J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:42:72)
    at HTMLBodyElementImpl._attach (J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:273:15)
    at HTMLBodyElementImpl._attach (J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:93:11)
    at HTMLHtmlElementImpl._attach (J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:273:15) ReferenceError: PostAffTracker is not defined
    at https://www.pluginboutique.com/users/login:2:3
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at Object.runInContext (vm.js:108:6)
    at processJavaScript (J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:128:10)
    at HTMLScriptElementImpl._eval (J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:65:7)
    at J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:31:22
    at Object.check (J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:91:11)
    at J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:110:12
    at HTMLScriptElementImpl._attach (J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:42:72)
    at HTMLBodyElementImpl._attach (J:\Junctions\Users\Pomax\Documents\Git\temp\pluginboutique\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:273:15)
HTMLInputElement {}
```

**Comment by domenic** [comment]
This is working as expected: if you open that URL https://www.pluginboutique.com/users/login in your browser, you will get the same error in your console. jsdom is just acting like a browser here.

(In the future, please use the issue template; it asks specifically "How does similar code behave in browsers?")
