### ISSUE TITLE
Regression v11.1.0 -> v11.2.0

### ISSUE THREAD

**Issue by oliviertassinari** [tmpvar/jsdom#1959]
### Basic info:

- **Node.js version:** v6.11.2
- **jsdom version:** v11.2.0

### Minimal reproduction case

```sh
git clone git@github.com:callemall/material-ui.git
cd material-ui
git checkout a1a17995202db7f669451ad41690fc5e126a770c
yarn
yarn test:unit
```

or even better: https://github.com/callemall/material-ui/commit/a1a17995202db7f669451ad41690fc5e126a770c

> Error: Uncaught [TypeError: Illegal invocation]
    at reportException (/tmp/material-ui/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:63:24)
    at invokeEventListeners (/tmp/material-ui/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:211:9)
    at HTMLLIElementImpl._dispatch (/tmp/material-ui/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:111:7)
    at Object.exports.fireFocusEventWithTargetAdjustment (/tmp/material-ui/node_modules/jsdom/lib/jsdom/living/helpers/focusing.js:73:10)
    at HTMLLIElementImpl.focus (/tmp/material-ui/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:65:14)
    at HTMLLIElement.focus (/tmp/material-ui/node_modules/jsdom/lib/jsdom/living/generated/HTMLElement.js:49:21)
    at Object.Menu._this.handleEnter [as onEnter] (/tmp/material-ui/src/Menu/Menu.js:113:27)
    at Object.Popover._this.handleEnter [as onEnter] (/tmp/material-ui/src/internal/Popover.js:228:18)
    at Object.Grow._this.handleEnter [as onEnter] (/tmp/material-ui/src/transitions/Grow.js:81:18)
    at Transition.performEnter (/tmp/material-ui/src/internal/Transition.js:235:15)
    at Transition.componentDidMount (/tmp/material-ui/src/internal/Transition.js:167:12)

### How does similar code behave in browsers?

It's working on [IE11, Firefox 45, Safari 10.1, Edge 14, Chrome 49](https://circleci.com/gh/callemall/material-ui/6201?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), jsdom v11.1.0 but [fails with jsdom v11.2.0](https://circleci.com/gh/callemall/material-ui/6203#tests/containers/0).

**Comment by domenic** [comment]
This didn't follow the definition of minimal reproduction case and the example in the issue template---especially the part about no third-party libraries. Let me close this until that can be fixed. Please ping this thread when the OP is updated with such an example.

**Comment by oliviertassinari** [comment]
> the example in the issue template---especially the part about no third-party libraries

Sorry, I have missed that part.

> Please ping this thread when the OP is updated with such an example.

We will stay on v11.1.0 for now. I believe I would need to understand the internal of jsdom post a minimal reproduction example. Let's wait and see if we are the only one affected.

**Comment by rsadza** [comment]
I had the same issue on v11.2.0, using v11.1.0 it still works. Accessing the view property of a UI event triggers the error.

The issue surfaced when we triggered a focus event on an element while also using jQuery. jQuery adds the focusin and focusout events, in which it tries to access the properties of the original focus event.

It can be reproduced via:
```
const jsdom = require("jsdom");
const JSDOM = jsdom.JSDOM;

var dom = new JSDOM('', {
    contentType: "text/html"
});

var document = dom.window.document;

var testInput = document.createElement("INPUT");
document.body.appendChild(testInput);
testInput.addEventListener('focus', function(e) {
    console.log(e['currentTarget']); // outputs "HTMLInputElement {}"
    console.log(e['altKey']); // outputs "undefined"
    console.log(e['view']); // triggers the "Illegal invocation" error
});
testInput.focus();
```

The following error is triggered:
```
TypeError: Illegal invocation
    at FocusEvent.get [as view] (/projects/bar/node_modules/jsdom/lib/jsdom/living/generated/UIEvent.js:83:13)
    at HTMLInputElement.<anonymous> (/projects/bar/tests/ThirdParty/jsdom-focus-test.js:15:18)
    at invokeEventListeners (/projects/bar/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:195:27)
    at HTMLInputElementImpl._dispatch (/projects/bar/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at Object.exports.fireFocusEventWithTargetAdjustment (/projects/bar/node_modules/jsdom/lib/jsdom/living/helpers/focusing.js:73:10)
    at HTMLInputElementImpl.focus (/projects/bar/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:65:14)
    at HTMLInputElement.focus (/projects/bar/node_modules/jsdom/lib/jsdom/living/generated/HTMLElement.js:49:21)
```

The expected behavior would be that the window is returned.

**Comment by sightmachinephil** [comment]
Well described. Also seeing the same, and also observing it's fixed @ `11.1.0`

**Comment by domenic** [comment]
Great report @rsadza, this is exactly what we've been hoping for. Now that we have this, we can actually work on a fix. Will reopen!

**Comment by TimothyGu** [comment]
See https://github.com/tmpvar/jsdom/pull/1979.

**Comment by oliviertassinari** [comment]
@TimothyGu Thanks for the fix 👏 !
