### ISSUE TITLE
Could not parse CSS stylesheet

### ISSUE THREAD

**Issue by caub** [tmpvar/jsdom#1995]
```js
var fetch=require('../node-fetch/lib'); // latest (2+)
var {JSDOM}=require('../jsdom'); // latest (11.2+)

var [bbfc='U',stars='3']=process.argv.slice(2); // https://codegolf.stackexchange.com/q/143808/7459

(async()=>{
	for(var i=0;i<1;i++){
		var t= await fetch(`https://www.theguardian.com/film+tone/reviews?page=${i}`).then(r=>r.text());
		var d=new JSDOM(t).window.document;
		var ul=d.querySelector('ul.l-row');
		console.log(ul.children.length)
	}
})()
.catch(console.error)
```

throws: 

```
Error: Could not parse CSS stylesheet
    at exports.evaluateStylesheet (/home/caub/dev/jsdom/lib/jsdom/living/helpers/stylesheets.js:18:21)
    at HTMLStyleElementImpl._attach (/home/caub/dev/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:23:5)
    at HTMLHeadElementImpl._attach (/home/caub/dev/jsdom/lib/jsdom/living/nodes/Node-impl.js:281:15)
```

I guess it's more an error from CSSOM, would there be a way to still read the markup, even with this CSS error (which doesn't really matter in my case)

**Comment by caub** [comment]
Hmm ok, it still continue to parse, I just need to check how to make it more silent (turn off the `elementImpl._ownerDocument._defaultView._virtualConsole.emit("jsdomError", error);`)
