### ISSUE TITLE
Last release breaks the build when using it together with React DOM

### ISSUE THREAD

**Issue by nescalante** [tmpvar/jsdom#2001]
Basically when using

```jsx
<svg style={{ foo: 'bar' }} />
```

with React. 

Basically the issue is that `node.style` is undefined now.

Just in case, this is my stack trace:

```
TypeError: Cannot set property 'height' of undefined
      at Object.setValueForStyles (node_modules/react-dom/lib/CSSPropertyOperations.js:195:26)
      at ReactDOMComponent._updateDOMProperties (node_modules/react-dom/lib/ReactDOMComponent.js:880:29)
      at ReactDOMComponent.mountComponent (node_modules/react-dom/lib/ReactDOMComponent.js:514:12)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactDOMComponent.mountChildren (node_modules/react-dom/lib/ReactMultiChild.js:238:44)
      at ReactDOMComponent._createInitialChildren (node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
      at ReactDOMComponent.mountComponent (node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactDOMComponent.mountChildren (node_modules/react-dom/lib/ReactMultiChild.js:238:44)
      at ReactDOMComponent._createInitialChildren (node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
      at ReactDOMComponent.mountComponent (node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactDOMComponent.mountChildren (node_modules/react-dom/lib/ReactMultiChild.js:238:44)
      at ReactDOMComponent._createInitialChildren (node_modules/react-dom/lib/ReactDOMComponent.js:697:32)
      at ReactDOMComponent.mountComponent (node_modules/react-dom/lib/ReactDOMComponent.js:516:12)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at mountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:104:32)
      at ReactReconcileTransaction.perform (node_modules/react-dom/lib/Transaction.js:140:20)
      at batchedMountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:126:15)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:97:27)
      at Object._renderNewRootComponent (node_modules/react-dom/lib/ReactMount.js:320:18)
      at Object._renderSubtreeIntoContainer (node_modules/react-dom/lib/ReactMount.js:401:32)
      at Object.render (node_modules/react-dom/lib/ReactMount.js:422:23)
      at Object.renderIntoDocument (node_modules/react-dom/lib/ReactTestUtils.js:79:21)
      at renderWithOptions (node_modules/enzyme/build/react-compat.js:200:24)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:94:59)
      at mount (node_modules/enzyme/build/mount.js:19:10)
```

This is the code (transpiled) from the function that breaks in React DOM lib (see `var style = node.style;`):

```
setValueForStyles: function (node, styles, component) {
    if (process.env.NODE_ENV !== 'production') {
      ReactInstrumentation.debugTool.onHostOperation({
        instanceID: component._debugID,
        type: 'update styles',
        payload: styles
      });
    }

    var style = node.style;
    for (var styleName in styles) {
      if (!styles.hasOwnProperty(styleName)) {
        continue;
      }
      if (process.env.NODE_ENV !== 'production') {
        warnValidStyle(styleName, styles[styleName], component);
      }
      var styleValue = dangerousStyleValue(styleName, styles[styleName], component);
      if (styleName === 'float' || styleName === 'cssFloat') {
        styleName = styleFloatAccessor;
      }
      if (styleValue) {
        style[styleName] = styleValue;
      } else {
        var expansion = hasShorthandPropertyBug && CSSProperty.shorthandPropertyExpansions[styleName];
        if (expansion) {
          // Shorthand property that IE8 won't like unsetting, so unset each
          // component to placate it
          for (var individualStyleName in expansion) {
            style[individualStyleName] = '';
          }
        } else {
          style[styleName] = '';
        }
      }
    }
  ```

I am not sure if this is a bug from `jsdom` or a bug from `react-dom`, the thing is that the issue started to happen after last release.

Thanks for your help

------

Edit (thanks to @graingert):

## Minimal reproduction case

https://runkit.com/graingert/59d64b929dc8c10012b8c118

## How does similar code behave in browsers?

https://jsfiddle.net/wuv2kovb/1/

**Comment by Sebmaster** [comment]
Probably `node` is not actually an HTML node it probably expects. `Element.style` is definitely a thing still from us...

```js
const JSDOM = require("jsdom").JSDOM;

const jsdom = new JSDOM("<div></div>");
const doc = jsdom.window.document;
console.log(doc.querySelector('div').style)
```

**Comment by domenic** [comment]
I don't see jsdom in that stack trace at all, so this is almost certainly an issue with one of those libraries instead.

**Comment by nescalante** [comment]
closing, still investigating.
If something new comes I will let you know.
Thanks for your help

**Comment by nescalante** [comment]
@Sebmaster:

```js
const JSDOM = require("jsdom").JSDOM;

const jsdom = new JSDOM("<svg></svg>");
const doc = jsdom.window.document;
console.log(doc.querySelector('svg').style)
```

with 11.3.0:

```
> test $ node jsdom.js
undefined
```

with 11.2.0:

```
> test $ node jsdom.js
CSSStyleDeclaration {
  _values: {},
  _importants: {},
  _length: 0,
  _onChange: [Function] }
```

Is this ok?

**Comment by Sebmaster** [comment]
Ah. Since we don't implement SVG, that's just an `Element`, which does not implement `style`. That changed with this release. 😞

**Comment by nescalante** [comment]
will that remain that way?

**Comment by Sebmaster** [comment]
This might give us a renewed reason to actually go start implementing SVG, but it's probably gonna be some time before that happens.

**Comment by zemirco** [comment]
We've got the same problem. Currently the tests are failing https://travis-ci.org/HBM/md-components/builds/283054614. Our current solution is pinning jsdom to 11.2.0 https://github.com/HBM/md-components/pull/382. At least the tests are green now.

What would you recommend for the future? You said it'll take some time to implement SVG.

**Comment by graingert** [comment]
@Sebmaster any monkey patch to add the feature back in?

**Comment by Sebmaster** [comment]
@graingert If you wanna go into totally unsupported land, patch [this function](https://github.com/tmpvar/jsdom/blob/a7a64987a6ddc9f903e6512e700497b00ed372ea/lib/jsdom/living/nodes/Document-impl.js#L367) to return `HTMLUnknownElement` instead of `Element`. Not sure if you can get to all the object refs you need though.

**Comment by graingert** [comment]
@nescalante FYI, this issue has nothing to do with React, can you update the issue title accordingly?

### Basic info:

- **Node.js version:** 8.6
- **jsdom version:** 11.3.0

### Minimal reproduction case
https://runkit.com/graingert/59d64b929dc8c10012b8c118

### How does similar code behave in browsers?
https://jsfiddle.net/wuv2kovb/1/

**Comment by graingert** [comment]
@Sebmaster that won't work because it will lowercase camelCase attributes, eg viewBox.

**Comment by graingert** [comment]
@Sebmaster is that:

>     Fixed the element interface used when creating many of the more obscure elements.

Can you link to the specific commit that did that?

**Comment by Sebmaster** [comment]
8ca057fbbc3c5aeb97eac8618eccb4b710e88cd8 was the commit that changed this initially.

**Comment by BruceHubbard** [comment]
I just hit this problem as well.  Took a little while to track it down since jsdom doesn't appear in the stacktrace.  Downgrading to 11.2 fixed the problem but there is definitely a breaking change with 11.3.

**Comment by domenic** [comment]
I don't classify this as a breaking change because it's taking an unsupported scenario (SVG element DOMs, which are not implemented) and moving how they work from one broken, non-spec-compliant implementation (being HTMLUnknownElements) to another, more-spec-compliant implementation (being Element, which at least is what non-SVG-supporting browsers would return).

I understand it causes pain for people for whom the broken version was previously running their code, but that code wasn't really supported, and didn't match browser behavior at all previously, so perhaps it is a good thing this change draws attention to the problem.

Hopefully we can start on some basic SVG support, and there are some open PRs with exactly that. That will be a proper resolution, but your code will still behave pretty differently, as it will then match browsers instead of being weird HTMLUnknownElements.

**Comment by graingert** [comment]
@domenic 

> and there are some open PRs with exactly that

can you link those?

**Comment by TimothyGu** [comment]
@graingert #1445, #1946.
