### ISSUE TITLE
Support for Web Workers?

### ISSUE THREAD

**Issue by drewish** [tmpvar/jsdom#2020]
### Basic info:

- **Node.js version:** v8.6.0
- **jsdom version:** 11.3.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  url: "http://example.com/",
};
const dom = new JSDOM(`
  <!DOCTYPE html><html><head></head><body></div></body></html>
`, options);

var w = new dom.window.Worker("demo_workers.js");
```

```
var w = new dom.window.Worker("demo_workers.js");
        ^

TypeError: dom.window.Worker is not a constructor
    at Object.<anonymous> (/Users/andrew/projects/swagger-linter/no-worker.js:10:9)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

### How does similar code behave in browsers?

You'd probably get the error that the file doesn't exist but `Worker` would be defined.

**Comment by rrcobb** [comment]
Seconded, this would be awesome

**Comment by jcjolley** [comment]
+1

**Comment by TimothyGu** [comment]
Can people refrain from adding +1 comments? They are not helpful.

Fixing this will depend on Worker support in Node.js core, which is already supported by [Ayo.js](https://github.com/ayojs/ayo) but yet to be backmerged into Node.js. Both the primary author of the feature and I are unfortunately short on time to make this happen soon.

**Comment by kapouer** [comment]
People like @jcjolley might have overlooked (being so overwhelmed by trump election) this 2016 github feature: [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments).

**Comment by RangerMauve** [comment]
Now that node [supports the worker threads API](https://nodejs.org/dist/latest-v10.x/docs/api/worker_threads.html) should this be investigated again?

**Comment by segevfiner** [comment]
This would be quite cool to have, basically we will need our own Worker/SharedWorker classes that use the worker_threads inside with their own entry script that wraps around the user supplied script and creates a web worker like environment, e.g. `importScript`, `self` and so on.
