### ISSUE TITLE
Dep: Request Promise Core issue

### ISSUE THREAD

**Issue by jarodium** [tmpvar/jsdom#2040]
### Basic info:

- **Node.js version:** v8.8.0
- **jsdom version:** 11.3.0
- **environment :** rasperry pi running Linux p1 4.9.59+ #1047 armv6l GNU/Linux

### Minimal reproduction case
```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

Execution yields:

/var/www/node_modules/request-promise-core/configure/request2.js:34
    var originalInit = options.request.Request.prototype.init;
                                               ^

TypeError: Cannot read property 'prototype' of undefined
    at module.exports (/var/www/node_modules/request-promise-core/configure/request2.js:34:48)
    at Object.<anonymous> (/var/www/node_modules/request-promise-native/lib/rp.js:15:1)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/node_modules/jsdom/lib/api.js:6:17)

**Comment by domenic** [comment]
I think the team will be unable to help with this as none of us run Node on a Raspberry pi, but maybe someone from the community will! Good luck!

**Comment by jarodium** [comment]
Which versions do you know it is properly running jsdom? I guess it should not matter if i'm running in a Raspberry Pi as the code should work everywhere.

**Comment by domenic** [comment]
That code works fine in Node v8.8.0 / jsdom v11.3.0 on other computers.

**Comment by jarodium** [comment]
Ok. Will try to fiddle with this a little more.
Thank you for the help :)

**Comment by michalcafe** [comment]
I had the same issue and I had to install `request@2.83`.
npm installed `request@2.85` because of how `jsdom` specifies the version in `package.json` (`"^2.83"`)
