### ISSUE TITLE
Problems With Canvas

### ISSUE THREAD

**Issue by SeunLanLege** [tmpvar/jsdom#2051]
### Basic info:

- **Node.js version:** v8.9.0
- **jsdom version:** v11.3

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

```js
const { window } = new JSDOM(`<!doctype html>
    <html>
        <body>
            <div id="map"></div>
            <script id="lol" src="https://js.api.here.com/v3/3.0/mapsjs-core.js" type="text/javascript" 
            charset="utf-8"></script>
            <script src="https://js.api.here.com/v3/3.0/mapsjs-service.js" type="text/javascript" charset="utf-8"></script>
            <script src="https://js.api.here.com/v3/3.0/mapsjs-ui.js" type="text/javascript"></script>
            <script src="https://js.api.here.com/v3/3.0/mapsjs-mapevents.js" type="text/javascript"></script>
            <script src="https://js.api.here.com/v3/3.0/mapsjs-clustering.js" type="text/javascript"></script>
            <script src="https://js.api.here.com/v3/3.0/mapsjs-places.js" type="text/javascript"  charset="utf-8"></script>
        </body>
    </html>`,
    {
        runScripts: "dangerously",
        resources: "usable",
        url: "http://localhost:8080"
    });
... some code ommitted...
window.document.addEventListener('DOMContentLoaded', () => {
            setImmediate(() => {
                const pixelRatio = 2

                const credentials = { app_id: HERE_APP_ID, app_code: HERE_APP_CODE };

                const here = new window.H.service.Platform({
                    ...credentials,
                    useHTTPS: true
                });
                const mapTileService = here.getMapTileService({ type: 'base' });
                const baseLayer = mapTileService.createTileLayer(
                    'maptile',
                    'reduced.day',
                    pixelRatio === 1 ? 256 : 512,
                    'png8',
                    { ppi: pixelRatio === 1 ? '72' : '320' }
                );

                // Create Map
                const map = new window.H.Map(document.getElementById("map"), baseLayer, {
                    center: { lat: 52.5, lng: 13.4 },
                    pixelRatio,
                    zoom: 10
                });
                // console.log("lolz", window.H)
                done()
            });
        });
```

when i try to run this, i get:

```
Uncaught TypeError: Cannot set property 'fill' of undefined
      at Ji.g (https://js.api.here.com/v3/3.0/mapsjs-core.js:186:120)
      at new Ji (https://js.api.here.com/v3/3.0/mapsjs-core.js:184:351)
      at new Q (https://js.api.here.com/v3/3.0/mapsjs-core.js:300:66)
      at Immediate._onImmediate (test/helpers/tooltip.test.js:27:29)
```

here-maps renders in a canvas

**Comment by asturur** [comment]
Did you install node-canvas?

**Comment by SeunLanLege** [comment]
i installed `"canvas-prebuilt": "^1.6.5-prerelease.1"`
