### ISSUE TITLE
<input type=file>'s value setter is faulty

### ISSUE THREAD

**Issue by TimothyGu** [tmpvar/jsdom#2063]
### Basic info:

- **Node.js version:** v9
- **jsdom version:** master

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  runScripts: "dangerously"
};
const dom = new JSDOM(`
  <input id=inp type=file>
  <script>document.getElementById("inp").value = "";</script>
`, options);
```

```
TypeError: 'set' on proxy: trap returned falsish for property 'length'
    at HTMLInputElementImpl.set value [as value] (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/living/nodes/HTMLInputElement-impl.js:195:27)
    at HTMLInputElement.set [as value] (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/living/generated/HTMLInputElement.js:893:25)
    at about:blank:1:38
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at Object.runInContext (vm.js:133:6)
    at processJavaScript (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:140:10)
    at HTMLScriptElementImpl._eval (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
    at /home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/living/nodes/Document-impl.js:91:11)
    at /home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/living/nodes/Document-impl.js:110:12
    at HTMLScriptElementImpl._attach (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:42:72)
    at HTMLBodyElementImpl._attach (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/living/nodes/Node-impl.js:290:15)
    at HTMLBodyElementImpl._attach (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/living/nodes/Element-impl.js:97:11)
    at HTMLHtmlElementImpl._attach (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/living/nodes/Node-impl.js:290:15)
    at HTMLHtmlElementImpl._attach (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/living/nodes/Element-impl.js:97:11)
    at DocumentImpl.insertBefore (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/living/nodes/Node-impl.js:230:22)
    at DocumentImpl.appendChild (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/living/nodes/Node-impl.js:328:17)
    at DocumentImpl.appendChild (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/living/nodes/Document-impl.js:401:18)
    at setChild (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/browser/htmltodom.js:240:18)
    at HTMLToDOM._parseWithParse5 (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/browser/htmltodom.js:47:7)
    at HTMLToDOM._doParse (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/browser/htmltodom.js:28:42)
    at HTMLToDOM.appendToDocument (/home/timothy-gu/dev/jsdom/jsdom/lib/jsdom/browser/htmltodom.js:24:17)
    at new JSDOM (/home/timothy-gu/dev/jsdom/jsdom/lib/api.js:68:29)
```

### How does similar code behave in browsers?

[Empties the element's `files` list.](https://html.spec.whatwg.org/multipage/input.html#dom-input-value-filename)

Regression from e7b68fa33db497aa1ddb5dbfc14f2bc53242e3a8 (which was committed w/o tests).

**Comment by Zirro** [comment]
Ah, I was dreading the day where I would end up committing a bug. There actually is a test related to this change - [input-value-invalidstateerr.html](https://github.com/w3c/web-platform-tests/blob/master/html/semantics/forms/the-input-element/input-value-invalidstateerr.html
), but as it was new to the roll it got enabled without changes to the manifest.

There is another test as well - [file-manual.html](https://github.com/w3c/web-platform-tests/blob/master/html/semantics/forms/the-input-element/file-manual.html), but as mentioned in an [earlier comment](https://github.com/tmpvar/jsdom/pull/2023#issuecomment-339983336) it can only be tested manually which isn't an option for us.

I will put together a fix and a new test which covers this case when I get home later today.

**Comment by TimothyGu** [comment]
Sorry, should've made it clear. I've got a more comprehensive fix coming later today.

**Comment by mjesun** [comment]
Hi! A quick question from [Jest](https://github.com/facebook/jest) folks; when this will get released?  And with which version? 🙂

(Just asking so we can update Jest's reference to `jsdom` when done). Thanks!
