### ISSUE TITLE
"Error: Not implemented:" navigation 

### ISSUE THREAD

**Issue by ramusus** [tmpvar/jsdom#2112]
After recent upgrade `jest` (which uses jsdom in background) from version 21.2.0 to 22.0.6 I have started getting error: `"Error: Not implemented:" navigation`

My code relies on `window.location` and I use in tests:

```
beforeEach(() => {
                window.location.href = `/ms/submission/?mybib`;
                window.location.search = '?mybib';
});
```

Is there a way to define a value of `window.location.search` using new version of jsdom?

**Comment by cpenarrieta** [comment]
I'm getting this error too
```
Error: Not implemented: navigation (except hash changes)
    at module.exports (...\node_modules\jsdom\lib\jsdom\browser\not-implemented.js:9:17)
    at navigateFetch (...\node_modules\jsdom\lib\jsdom\living\window\navigation.js:74:3)
```

**Comment by domenic** [comment]
jsdom does not support navigation, so setting window.location.href or similar will give this message. I'm not sure if Jest was just suppressing these messages before, or what.

This is probably something you should fix in your tests, because it means that if you were running those tests in the browser, the test runner would get completely blown away as you navigated the page to a new URL, and you would never see any tests results. In jsdom instead we just output a message to the console, which you can ignore if you want, or you can fix your tests to make them work better in more environments.

Anyway, I'd like to add more documentation on this for people, so I'll leave this issue open to track doing so.

**Comment by probablyup** [comment]
Totally get what you're saying. The recent Jest 22 update went from JSDOM 9 to 11 IIRC, so the behavior back in 9.x might have been quite different.

All that aside, I would love to see navigation implemented in JSDOM with some sort of flag to make it a no-op in terms of loading a different page. The library is very commonly used for testing purposes so, while perhaps a quirky request, it would be used often.

**Comment by domenic** [comment]
I don't think we should add a flag that makes your tests run different in jsdom than in browsers. Then your stuff could be broken in browsers (e.g. it could be redirecting users to some other page, instead of doing the action that your tests see happening) and you wouldn't even notice!

**Comment by probablyup** [comment]
Well in this case it wouldn't doing anything different, other than not unloading the current page context. I'd still expect `window.location.href` to be updated, etc.

**Comment by hontas** [comment]
@domenic I'm having the same issue and I was wondering if there is some sort of best practice to setup JSDOM with an app that sets `window.location.href`. Currently I am wrapping my production code in `try - catch` to not make the tests fail - how would you propose I do it instead?
Thankful for help 😅

**Comment by hontas** [comment]
Allow me to post the answer to my own question 😁
I simply replace the usages of `window.location = url;` and `window.location.href = url;` with
```js
window.location.assign(url);
```
and the in my tests I did:
```js
sinon.stub(window.location, 'assign');
expect(window.location.assign).to.have.been.calledWith(url);
```

Works like a charm - hope it can be of help to someone else 👍

**Comment by xixixao** [comment]
Agree this should work out of the box. We mock `window.location` at FB, but that conflicts with jsdom's `History` implementation.

**Comment by Zirro** [comment]
As a small team, we would certainly appreciate help from the larger projects that depend on us to properly implement navigation in jsdom.

If anyone is interested, https://github.com/jsdom/jsdom/pull/1913 could be a good place to start.

**Comment by vvo** [comment]
Possible solution is to rely on dependency injection/mock for the global object in unit tests.

Something like:

```js
it('can test', () => {
  const mockWindow = {location: {href: null}};
  fn({window: mockWindow});
  expect(mockWindow.href).toEqual('something');
});
```

This is not ideal but as said by @domenic:
> This is probably something you should fix in your tests, because it means that if you were running those tests in the browser, the test runner would get completely blown away as you navigated the page to a new URL

For now we live with this and yes we change our implementation code for tests which is considered bad practice but we also sleep well at night!

Happy testing

**Comment by zxiest** [comment]
@hontas's solution helped:

I did use `window.location.assign(Config.BASE_URL);` in my code.

And here's the test:
```
jest.spyOn(window.location, 'assign').mockImplementation( l => {
   expect(l).toEqual(Config.BASE_URL);
})

window.location.assign.mockClear();
```

**Comment by yvele** [comment]
Same problem, I'm using `window.location.search = foo;` in my code and I would like to test it using jsdom (and jest) 🤔

**Comment by yuri-sakharov** [comment]
After updating to jsdom 12.2.0 got error:
TypeError: Cannot redefine property: assign
on` const assign = sinon.stub(document.location, 'assign')`
how to fix it?

**Comment by nickhallph** [comment]
> After updating to jsdom 12.2.0 got error:
> TypeError: Cannot redefine property: assign
> on` const assign = sinon.stub(document.location, 'assign')`
> how to fix it?

```
sinon.stub(document.location, 'assign')
```

needs to be:

```
sinon.stub(window.location, 'assign')
```

you need to replace`document` with `window`

**Comment by yordis** [comment]
I have the following function 

```ts
export const isLocalHost = () => Boolean(
  window.location.hostname === 'localhost' ||
  // [::1] is the IPv6 localhost address.
  window.location.hostname === '[::1]' ||
  // 127.0.0.1/8 is considered localhost for IPv4.
  window.location.hostname.match(
    /^127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/
  )
);
```

for me to be able to test that it works I inject directly the `hostname`

```ts
it('#isLocalHost should return true for all the cases of localhost', () => {
    window.location.hostname = 'localhost';
    expect(isLocalHost()).toBeTruthy();

    window.location.hostname = '[::1]';
    expect(isLocalHost()).toBeTruthy();

    window.location.hostname = '127.0.0.1';
    expect(isLocalHost()).toBeTruthy();

    // Reset back the hostname to avoid issues with it
    window.location.hostname = '';
  });
```

But I am getting this error.

I don't expect `jsdom` to fully implement the navigation but at least add the keys and mock the functions.

**Comment by yuri-sakharov** [comment]
@nickhallph
I replaced it to `window.location` as you wrote but result the same 
`TypeError: Cannot redefine property: assign`
Any ideas?

**Comment by nielskrijger** [comment]
Same problem as @yuri-sakharov running mocha. 

By no means I seem able to replace/update/mock or do anything with `window.location.*`. The only way I see around this is creating my own custom window mock and change the entire codebase to depend on that, but that's just silly.

**Comment by tomturton** [comment]
> Allow me to post the answer to my own question 
> I simply replace the usages of `window.location = url;` and `window.location.href = url;` with
> 
> ```js
> window.location.assign(url);
> ```
> 
> and then in my tests I did:
> 
> ```js
> sinon.stub(window.location, 'assign');
> expect(window.location.assign).to.have.been.calledWith(url);
> ```
> 
> Works like a charm - hope it can be of help to someone else

@hontas and @zxiest 's answers looked promising, but I still get `Error: Not implemented: navigation (except hash changes)` when mocking `window.location.assign`.

Here is my Jest test:
```javascript
locationSpy = jest.spyOn(window.location, 'assign');

theFunctionWhatCallsWindowAssign();

locationSpy.mockImplementation((uri) => {
  expect(uri).toEqual('the-uri');
});

window.location.assign.mockClear();
```

using Jest v23.6.0

**Comment by tomturton** [comment]
> @hontas's solution helped:
> 
> I did use `window.location.assign(Config.BASE_URL);` in my code.
> 
> And here's the test:
> 
> ```
> jest.spyOn(window.location, 'assign').mockImplementation( l => {
>    expect(l).toEqual(Config.BASE_URL);
> })
> 
> window.location.assign.mockClear();
> ```

@zxiest's Jest version of @hontas' solution didn't work for me, but this did:

```javascript
window.location.assign = jest.fn();
expect(window.location.assign).toHaveBeenCalledWith('https://correct-uri.com');
window.location.assign.mockRestore();
```

**Comment by ggregoire** [comment]
The last answer worked for me, but I had to redefine `replace`:

```javascript
delete window.location
window.location = { replace: jest.fn() }
```

Hope it helps.

**Comment by RichardWright** [comment]
I'm getting TypeError: Cannot redefine property: assign with sinon 7.2.3 and jsdom 13.2.0. No idea why this works for some people and not others?

**Comment by RichardWright** [comment]
> The last answer worked for me, but I had to define `replace`:
> 
> ```js
> delete window.location
> window.location = { replace: jest.fn() }
> ```
> 
> Hope it helps.

Isn't this rather a nuclear option?

**Comment by sergioviniciuss** [comment]
This is what worked for me:
```javascript
global.window = Object.create(window);
    const url = 'http://localhost';
    Object.defineProperty(window, 'location', {
      value: {
        href: url,
      },
      writable: true,
    });
```

**Comment by yordis** [comment]
We used `pushState` to make this to work

```js
 window.history.pushState(
        {},
        '',
        'http://localhost/something/123?order=asc'
      );
```

**Comment by mpareja** [comment]
This is a difficult situation. JSDOM does not fully supports navigation (other than breadcrumbs) and JSDOM does not allow us to mock-out navigation. The end result is that *I can't write tests which ultimately attempt to trigger navigation*.

If JSDOM did learn to navigate (I'm not even sure what that means), maybe I could assert about being on the appropriate page. For my testing use cases, though, asserting the navigation was triggered, rather than actually performed, is much cleaner/faster. It's what I've historically done when testing using jsdom and now it's broken.

**Comment by beshoo** [comment]
> Allow me to post the answer to my own question 
> I simply replace the usages of `window.location = url;` and `window.location.href = url;` with
> 
> ```js
> window.location.assign(url);
> ```
> 
> and then in my tests I did:
> 
> ```js
> sinon.stub(window.location, 'assign');
> expect(window.location.assign).to.have.been.calledWith(url);
> ```
> 
> Works like a charm - hope it can be of help to someone else

That if you have control to the target url, but what if you are loading google or Instagram website. or any website? how can you solve this problem ?

**Comment by scriptex** [comment]
Based on answer from @chrisbateman I managed to get this working in a Jest environment. For anyone who is using Jest, here is my workaround:

```javascript
describe('', () => {
    const originalLocation = window.location;

    beforeEach(() => {
        delete window.location;

        window.location = {
            href: '',
        };
    });

    afterEach(() => {
        window.location = originalLocation;
    });

    it('', () => {
        // test here
    });
});
```

**Comment by hamzahamidi** [comment]
I solved this issue using this config. I wanted to rest redirection for has urls:
```javascript

    beforeEach(() => {
      delete global.window;
      global.window = {
        location: { replace: jest.fn(url => ({ href: url })) },
      };
    });
    it('should redirect hash url', () => {
      window.location.hash = '#/contrat?id=8171675304';
      global.window.location.href =
        'http://localhost:3000/#/contrat?id=8171675304';
      redirectHashUrl();

      expect(window.location.replace).toHaveBeenCalled();
    });

```

**Comment by aibolik** [comment]
@chrisbateman @hamzahamidi thanks, that solutions worked well. 

Maybe it's not a good practice, but we have some tests, those rely on location/host/hostname and other location properties. So mocking location as we want and restoring afterwards worked for me.

```js
const realLocation = window.location;

describe('bla bla', () => {
  afterEach(() => {
    window.location = realLocation;
  });

  it('test where I want to use hostname', () => {
    delete window.location;
    window.location = { 
      hostname: 'my-url-i-expect.com'
    };
    // check my function that uses hostname
  });
});
```

**Comment by elemanhillary** [comment]
> This is what worked for me:
> 
> ```js
>     global.window = Object.create(window);
>     const url = 'http://localhost';
>     Object.defineProperty(window, 'location', {
>       value: {
>         href: url,
>       },
>       writable: true,
>     });
> ```

it doesnot work on a `CI` like circleci

**Comment by vafanasenka** [comment]
> @hontas's solution helped:
> 
> I did use `window.location.assign(Config.BASE_URL);` in my code.
> 
> And here's the test:
> 
> ```
> jest.spyOn(window.location, 'assign').mockImplementation( l => {
>    expect(l).toEqual(Config.BASE_URL);
> })
> 
> window.location.assign.mockClear();
> ```

Thanks mate, you've saved me a day! :)

**Comment by jarrodmedrano** [comment]
None of these worked for me

**Comment by jasonfb** [comment]
In my case I'm testing for the query string, and since the **subject** of my spec **IS** the query string itself, I don't want to bypass it, but I'm happy to stub it out. in my case this worked well:
```
    let name = "utm_content"
    window.history.pushState({}, 'Test Title', '/test.html?utm_content=abc');
    expect(ParseUrlUtils.getParam(name)).toBe("abc")
```

Note that here it doesn't matter what the title of the window is and it also doesn't matter that it is `/test.html` (which is not real), all that matters is that the query string is fetched correctly (this passes)

**Comment by juanparati** [comment]
The issue with examples is that methods and getters are not use. What I do is basically replace Location object by URL object. URL has all the properties of Location (search, host, hash, etc) and also methods (assign, replace...).

```
const realLocation = window.location;

describe('My test', () => {

    afterEach(() => {
        window.location = realLocation;
    });

    test('My test func', () => {

        // @ts-ignore
        delete window.location;

        // @ts-ignore
        window.location = new URL('http://google.com');

        // ...
    });
});

```

**Comment by ajeesh-s** [comment]
> I'm getting this error too
> 
> ```
> Error: Not implemented: navigation (except hash changes)
>     at module.exports (...\node_modules\jsdom\lib\jsdom\browser\not-implemented.js:9:17)
>     at navigateFetch (...\node_modules\jsdom\lib\jsdom\living\window\navigation.js:74:3)
> ```

**Comment by EduardoFLima** [comment]
> @hontas's solution helped:
> 
> I did use `window.location.assign(Config.BASE_URL);` in my code.
> 
> And here's the test:
> 
> ```
> jest.spyOn(window.location, 'assign').mockImplementation( l => {
>    expect(l).toEqual(Config.BASE_URL);
> })
> 
> window.location.assign.mockClear();
> ```

This worked for me, thanks! However I had to use the `done` argument from jest test(), otherwise I wouldn't be sure that the expect was evaluated and the test might had ended successfully anyway:

> ```
> it('should', (done) => {
> jest.spyOn(window.location, 'assign').mockImplementation( l => {
>    expect(l).toEqual(Config.BASE_URL);
>    done();
> })
> 
> window.location.assign.mockClear();
> }
> ```

**Comment by captain-yossarian** [comment]
@hontas Does not work for me :( Unable to rewrite assign/replace property

**Comment by nareshbhatia** [comment]
Is there any way to find out which test is triggering the "Not implemented: navigation" message? I have a suite of 43 tests - the error is being displayed only once and it keeps bouncing around. I can't tell which test to fix!!! The stack trace gives me no indication of the culprit:

```
console.error
  Error: Not implemented: navigation (except hash changes)
      at module.exports (/Users/naresh/projects/mobx-state-router/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
      at navigateFetch (/Users/naresh/projects/mobx-state-router/node_modules/jsdom/lib/jsdom/living/window/navigation.js:76:3)
      at exports.navigate (/Users/naresh/projects/mobx-state-router/node_modules/jsdom/lib/jsdom/living/window/navigation.js:54:3)
      at Timeout._onTimeout (/Users/naresh/projects/mobx-state-router/node_modules/jsdom/lib/jsdom/living/nodes/HTMLHyperlinkElementUtils-impl.js:81:7)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7) undefined

    at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
    at module.exports (node_modules/jsdom/lib/jsdom/browser/not-implemented.js:12:26)
    at navigateFetch (node_modules/jsdom/lib/jsdom/living/window/navigation.js:76:3)
    at exports.navigate (node_modules/jsdom/lib/jsdom/living/window/navigation.js:54:3)
    at Timeout._onTimeout (node_modules/jsdom/lib/jsdom/living/nodes/HTMLHyperlinkElementUtils-impl.js:81:7)
```

**Comment by infernalmaster** [comment]
> @hontas Does not work for me :( Unable to rewrite assign/replace property

As I understand jest changed something in new version ("jest": "^26.0.1") so this works right now:

```js
// Mock
  Object.defineProperty(window, 'location', {
    value: {
      pathname: '/terminals',
      assign: jest.fn(),
    },
  });

// Then test
expect(window.location.assign).toBeCalledWith('/auth');

```

**Comment by annaemu** [comment]
I am currently using Jest `26.0.1` and the below works for me:

1. Use `window.location.assign(url)` to change the window location.

2. Mock the location object as follows (note that not deleting and rebuilding the object first still results in the not implemented error in the noted version of Jest and earlier I think, also `Object.defineProperty` doesn't work and still results in the error):
```
delete window.location;
window.location = {
    href: '',
    hostname: '',
    pathname: '',
    protocol: '',
    assign: jest.fn(),
    ...initial,
};
```

3. Assert with:
```
expect(window.location.assign).toBeCalledWith(url);
```

It would be really nice if jest allowed us to easily mock location without all of these constant issues and changes. I was previously using just `window.location.assign = jest.fn()` without any problems for a long time, then I upgraded from v24 and now this.

**Comment by ryuuji3** [comment]
Is there a good reason that the Window APIs were locked/frozen?
It seems like that's the barrier for people trying to work-around navigation not being implemented.

If not, can we just not freeze them? I don't think even browsers are that strict at preventing you from altering window objects.

**Comment by domenic** [comment]
If you have an example of jsdom behaving differently from browsers, please file an issue following the issue template (including the jsbin or similar showing browser behavior).

**Comment by mattcphillips** [comment]
Is anyone else running into the same `Error: Not implemented: navigation (except hash changes)` during Jest tests that fire a click event on an anchor element with an `href`? For my tests, I'm spying on a function that gets called `onClick` and making assertions about that so I need to actually fire the click event on the anchor element.

The solutions above related to mocking `window.location` work for me where I am explicitly calling `window.location.replace` or `window.location.assign`, but don't help for this case where the navigation originates from an anchor element being clicked.

Any ideas on solutions? Thanks!

**Comment by domenic** [comment]
How would you test that code in a browser? Keep in mind that in the browser clicking on the link would blow away your whole page and throw away any test results. So whatever you would do to prevent that, will also prevent the much-less-dramatic warning message jsdom outputs to the console.

**Comment by romanhavr** [comment]
In my situation project upgraded Jest from 23 to 26 version.
I had a problem with `location.search`. Had the same error `Error: Not implemented: navigation`.
Module I tested gets values of search query params.
Next implementation worked for me:
```
beforeAll(() => {
  delete window.location;
  window.location = new URL('your URL');
})

afterAll(() => {
  window.location.search = '';
})
```

**Comment by Sabrinovsky** [comment]
@mattcphillips have you figured out how to fix this? i'm also having problem when clicking

**Comment by mattcphillips** [comment]
@Sabrinovsky No, I ended up just adding a script to the `setupFiles` in my jest config that would swallow the console errors coming from jsdom navigation so that they weren't cluttering up our tests. More of a bandaid than anything else, but it sounded like these errors are to be expected in our test setup.

Here's the script that I run before my tests:
```
// There should be a single listener which simply prints to the
// console. We will wrap that listener in our own listener.
const listeners = window._virtualConsole.listeners('jsdomError');
const originalListener = listeners && listeners[0];

window._virtualConsole.removeAllListeners('jsdomError');

// Add a new listener to swallow JSDOM errors that orginate from clicks on anchor tags.
window._virtualConsole.addListener('jsdomError', error => {
  if (
    error.type !== 'not implemented' &&
    error.message !== 'Not implemented: navigation (except hash changes)' &&
    originalListener
  ) {
    originalListener(error);
  }

  // swallow error
});
```

**Comment by Akhil-bridge** [comment]
This worked for me.

```
delete global.window.location
global.window.location = { href: 'https://test.com' }
```

**Comment by hendrawanhadikusuma** [comment]
This worked for me

`delete window.location
window.location = { assign: jest.fn() }`

**Comment by devniel** [comment]
If you get `TypeError: Cannot assign to read only property 'assign' of object '[object Location]'`, then using something like this in your `jest.setup.ts`:

```
global.window = Object.create(window);
Object.defineProperty(window, 'location', {
  value: {
    ...window.location,
  },
  writable: true,
});
````

**Comment by s-taylor** [comment]
If it helps anyone this is what I did. We are using mocha not jest so only have sinon available.
```
exports.jsdom = new JSDOM('<!doctype html><html><body></body></html>', { url: 'http://localhost' });
const { window } = exports.jsdom;

/* This enables stubbing window.location.assign for url changes */
const { location } = window;
delete window.location;
window.location = { ...location, assign: () => {} };
```

You can then freely stub...
`const assignStub = sandbox.stub(window.location, 'assign');`

**Comment by blephy** [comment]
> @Sabrinovsky No, I ended up just adding a script to the `setupFiles` in my jest config that would swallow the console errors coming from jsdom navigation so that they weren't cluttering up our tests. More of a bandaid than anything else, but it sounded like these errors are to be expected in our test setup.
> 
> Here's the script that I run before my tests:
> 
> ```js
> // There should be a single listener which simply prints to the
> // console. We will wrap that listener in our own listener.
> const listeners = window._virtualConsole.listeners('jsdomError');
> const originalListener = listeners && listeners[0];
> 
> window._virtualConsole.removeAllListeners('jsdomError');
> 
> // Add a new listener to swallow JSDOM errors that orginate from clicks on anchor tags.
> window._virtualConsole.addListener('jsdomError', error => {
>   if (
>     error.type !== 'not implemented' &&
>     error.message !== 'Not implemented: navigation (except hash changes)' &&
>     originalListener
>   ) {
>     originalListener(error);
>   }
> 
>   // swallow error
> });
> ```

This worked for me with angular.
All stub workaround provided in other messages doesn't work with angular.

**Comment by s-taylor** [comment]
Second attempt at this, my previous attempt broke using the `history` lib, presumably because `assign` was no longer a `getter`.

This solves that issue...
```
// This makes window.location.assign writable so sinon can stub
function patchLocation(location) {
  const clone = Object.create(Object.getPrototypeOf(location));
  const descriptors = Object.getOwnPropertyDescriptors(location);
  descriptors.assign.writable = true;
  descriptors.assign.configurable = true;
  Object.defineProperties(clone, descriptors);
  return clone;
}

const { location } = window;
delete window.location;
window.location = patchLocation(location);
```

**Comment by fooey** [comment]
> 
> 
> @Sabrinovsky No, I ended up just adding a script to the `setupFiles` in my jest config that would swallow the console errors coming from jsdom navigation so that they weren't cluttering up our tests. More of a bandaid than anything else, but it sounded like these errors are to be expected in our test setup.
> 
> Here's the script that I run before my tests:
> 
> ```js
> // There should be a single listener which simply prints to the
> // console. We will wrap that listener in our own listener.
> const listeners = window._virtualConsole.listeners('jsdomError');
> const originalListener = listeners && listeners[0];
> 
> window._virtualConsole.removeAllListeners('jsdomError');
> 
> // Add a new listener to swallow JSDOM errors that orginate from clicks on anchor tags.
> window._virtualConsole.addListener('jsdomError', error => {
>   if (
>     error.type !== 'not implemented' &&
>     error.message !== 'Not implemented: navigation (except hash changes)' &&
>     originalListener
>   ) {
>     originalListener(error);
>   }
> 
>   // swallow error
> });
> ```

Thank you for this!

For anyone who wants to make TypeScript happy

```typescript
import { VirtualConsole } from 'jsdom';

declare global {
  interface Window {
    _virtualConsole: VirtualConsole;
  }
}
```

**Comment by Whoaa512** [comment]
What's the workaround here if the navigation event is coming from a deeply nested click on an element wrapped in an `<a>` tag? I'm not able to easily stub the onClick handler to add a `e.preventDefault()` and I didn't see and easy way to intercept this error and know if it was an anchor click or location.assign

**Comment by markoboy** [comment]
I can see that there has been a lot of struggle with this from a lot of people.

In my case I had an issue while clicking on html anchor tag element in order to test that analytics are fired correctly. None of the above solutions worked.

In the end it was something very simple...

```js
        clickedLink = getAllByRole('link').find((link) =>
          link.textContent?.includes(getDirectionsText),
        );

        clickedLink.addEventListener(
          'click',
          (event) => event.preventDefault(),
          false,
        );

        userEvent.click(clickedLink);
```

Attaching a click event listener to the anchor tag before emitting the click event does the trick.

I hope this will help someone else facing the same issue.

**Comment by dnalbach** [comment]
For anyone who is interested, here's how I adapted the @markoboy solution in my Jest test with Vue3:
```
const button = wrapper.find('#some_id');
button.wrapperElement.addEventListener('click', (event) => event.preventDefault(), false);
button.trigger('click');
```

**Comment by jhnance** [comment]
> Is anyone else running into the same `Error: Not implemented: navigation (except hash changes)` during Jest tests that fire a click event on an anchor element with an `href`? For my tests, I'm spying on a function that gets called `onClick` and making assertions about that so I need to actually fire the click event on the anchor element.
> 
> The solutions above related to mocking `window.location` work for me where I am explicitly calling `window.location.replace` or `window.location.assign`, but don't help for this case where the navigation originates from an anchor element being clicked.
> 
> Any ideas on solutions? Thanks!

@mattcphillips 

I think this is the issue I just ran into. The response below yours is what triggered a realization for me. I was testing this in the browser by setting a breakpoint on the `beforeunload` event. So, I just added the same thing in my test and got it to work. Still get the annoying console logs but the test is passing.

However, I will say that I'm a bit confused why the test passes on its own without this kind of event listener, but needs the event listener when run in the same file as other tests. Probably something else I'm missing here that could make my test better...

Anyway, here's what I tried. Again, this is for an anchor element with an `onClick`:

```javascript
window.addEventListener('beforeunload', function () {
  // make your assertion here based on w/e it is your anchor's click handler does
});
```

**Comment by kevr** [comment]
> How would you test that code in a browser? Keep in mind that in the browser clicking on the link would blow away your whole page and throw away any test results. So whatever you would do to prevent that, will also prevent the much-less-dramatic warning message jsdom outputs to the console.

In all of your replies in this thread, you seem to be completely missing the fact that there are ways to test against the DOM and changes in the location, as is done when testing frameworks like React/Angular/Vue. We are able to fire events which manipulate the DOM, and this is pretty much what's tested everywhere in these front-end frameworks. We aren't testing inside of a browser; we're testing using jest or other test frameworks; we just need to be able to actually stub out these for things like React to even navigate properly. JSDom completely breaks in this case, apparently.

It's not our test code that's the problem. It's that this functionality is just missing from JSDom which would help these frameworks in that sense. All of our workarounds are straight up hacks to work around the fact that this implementation is just missing.

Perhaps you could help users here with some direction on doing this, rather than telling everybody to go fix their "broken code" that wasn't even written by them. Nothing you've said here has been helpful or even really truthful at all.

**Comment by domenic** [comment]
jsdom is not intended to provide a testing library. We're providing a browser implementation. If it's not suitable for your purposes, then you should not use it.

**Comment by kevr** [comment]
> jsdom is not intended to provide a testing library. We're providing a browser implementation. If it's not suitable for your purposes, then you should not use it.

Makes much more sense.

**Comment by Focus-me34** [comment]
Hey guys!

I found a solution without using mock or Object.defineProperty or by creating a. new window etc. ...
Here it is :

```
  afterEach(() => {
      window.history.replaceState({}, "", decodeURIComponent(http://localhost/));
  });
```

I think the reason for the error we all had is that there's something wrong going on with the browser history in test env (I'm personally using react-router v6 with <BrowserRouter>).

Anyway, the code snippet above replaces the current URL with the one passed as the third argument of the .replaceState() function by manipulating not the URL directly, but the history of navigation.

More about this function here: https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState

Hope it was helpful! 🔥

**Comment by Andre-the-Viking** [comment]
> Is there a way to fail tests when `'Error: Not implemented: navigation (except hash changes)'` is thrown? I'm using vitest and couldn't find any type of console message that would actually fail the tests (info, warning etc). I'm trying to do something like
> 
> ```
> const spy = vi.spyOn(console, 'error').mockImplementation(() => {})
> expect(spy).toHaveBeenCalledWith('Error: Not implemented: navigation (except hash changes)')
> ```
> 
> to make sure that the navigation is happening or not happening. In my case it's important to make sure that the disabled link is not navigating anywhere on click

```js
  it("show a error message if the download fails", async () => {
....
    const spyConsoleError = jest
      .spyOn(console, "error")
      .mockImplementation(() => {});

....
    await waitFor(() => {
      expect(spyConsoleError).toHaveBeenCalledWith(
        expect.stringContaining(expectedConsoleError),
        undefined
      );
    });

.... // other expects...
    expect(messageError).toHaveBeenCalledWith({ message: expectedError });

**Comment by IuliiaBondarieva** [comment]
It seems that in some cases you just can't get rid of this error. :(

If you click on HyperlinkElement, you get to the `HTMLHyperlinkElementUtilsImpl` class, which at some point gets right into the `navigateFetch` function, which does nothing but throw an error
```
function navigateFetch(window) {
  // TODO:
  notImplemented("navigation (except hash changes)", window);
}
```

So if you use a HyperlinkElement in a test, you are doomed to this error.

For the helpless cases, I wrote a function to avoid noisy console error messages while not missing other cases:

```
const realError = console.error;

const disableConsoleError = () => {
    console.error = jest.fn();
};

const restoreConsoleError = () => {
    console.error = realError;
};

export const consoleErrorWrapper = (callback: () => void) => {
    disableConsoleError();
    callback();
    restoreConsoleError();
};
```

and I use it as `act` method from react:

```
it('should track click', async () => {
       consoleErrorWrapper(async () => {
            const trackClick = jest.spyOn(require('TrackingUtil'), 'trackClick');

            render(<Product product={productMock} />);
            const link = screen.getByTestId('product-link');

            await userEvent.click(link);

            expect(trackProducts).toHaveBeenCalled();
        });
 });
```

**Comment by nilslindemann** [comment]
As I see it, calling window.location.href is not an error by me. Throwing an error, because I do, is an error by jsdom. Not hiding this error from its output is an error by jest. So why change my workflow? The errors are made by others.

Until these people behave nicer, I out comment ...

```
window._virtualConsole.emit("jsdomError", error);
```

... in `node_modules/jsdom/lib/jsdom/browser/not-implemented.js`. The message will not be printed anymore.

**Comment by janeklb** [comment]
Yet-Another-Solution (TypeScript friendly). Only works if you have control over the `window.location.*` calls you want to test.

IMO this is actually best as it **explicitly** removes side-effect code from your business logic. If you want, you can then 


1. create a `windowLocation` module/file etc.
```ts
// adjust WindowLocation to accommodate all the window.location functionality you need

type WindowLocation = Pick<
  typeof window.location,
  'reload' | 'assign' | 'pathname' | 'href' | 'origin'
>;

export const windowLocation: WindowLocation = {
  reload: () => window.location.reload(),
  assign: (url) => window.location.assign(url),
  get pathname() {
    return window.location.pathname;
  },
  get href() {
    return window.location.href;
  },
  get origin() {
    return window.location.origin;
  },
};
```

2. replace all `window.location.*` calls with `windowLocation.*`
   eg.
   ```ts
   windowLocation.reload(); // instead of window.location.reload();
   ```

3. set up your test framework to mock access to this module
   eg. if you're using `jest`, update your `jest.setup.ts` / `setupFilesAfterEnv` file:
   ```ts
   type WindowLocationModule = typeof import('./path/to/windowLocation');
   jest.mock<>('./path/to/windowLocation', () => ({
     windowLocation: {
       assign: jest.fn(),
       href: 'https://fake.url/',
       origin: 'https://fake.url',
       pathname: '/',
       reload: jest.fn(),
     },
   }));
   ```

**Comment by joshkel** [comment]
Newer versions of jsdom have (understandably and correctly) marked more properties as non-configurable, so some of the workarounds provided here for mocking navigation functionality in unit tests don't work. However, it's possible to access jsdom's implementation methods and mock those instead. This is, of course, a dirty hack. Here's an example of what this looks like in Jest.

```ts
// Following web standards, many jsdom instance properties are read-only and
// non-configurable, which interferes with mocking.  Instead, we can find
// jsdom's implSymbol property to get at the JS logic underlying its Web IDL
// instances.
const implSymbol = Reflect.ownKeys(window.location).find((i) => typeof i === 'symbol')!;
const assign = jest
  .spyOn((window.location as any)[implSymbol], 'assign')
  .mockImplementation(() => {});

try {
  // Do the test.
} finally {
  assign.mockRestore();
}
```

**Comment by ravi-more** [comment]
> After recent upgrade `jest` (which uses jsdom in background) from version 21.2.0 to 22.0.6 I have started getting error: `"Error: Not implemented:" navigation`
> 
> My code relies on `window.location` and I use in tests:
> 
> ```
> beforeEach(() => {
>                 window.location.href = `/ms/submission/?mybib`;
>                 window.location.search = '?mybib';
> });
> ```
> 
> Is there a way to define a value of `window.location.search` using new version of jsdom?

not sure about the search but you try this to change the url:

```
window.history.pushState({}, 'Test page', '/dashboard');
  render(
    <MemoryRouter>
      <Component />
    </MemoryRouter>
  );
```
