### ISSUE TITLE
'Not implemented' util tries to call a method that is not implemented

### ISSUE THREAD

**Issue by vectart** [tmpvar/jsdom#866]
```
jsdom/lib/jsdom/browser/utils.js:9
      raise.call(this, "error", "NOT IMPLEMENTED" + (nameForErrorMessage ? ": 
            ^
TypeError: Cannot call method 'call' of undefined
    at new <anonymous> (/Users/marat/Dev/nodemailer-htmlpage-parser/node_modules/jsdom/lib/jsdom/browser/utils.js:9:13)
    at null._onTimeout (file://core.insightexpressai.com/adServer/GetInvite2.aspx?esi=true&bannerID=280513&referer=file::1:10133)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by domenic** [comment]
Fixed in 3.1.2.
